import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!;const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const SECRET=Deno.env.get("ARIA_RUNTIME_SHARED_SECRET")!;
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false,autoRefreshSession:false}});
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const eq=(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0};
const auth=async(r:Request)=>{const h=r.headers.get("authorization")??"";const t=h.startsWith("Bearer ")?h.slice(7):null;if(t&&SECRET&&eq(t,SECRET))return true;const a=r.headers.get("x-aria-autonomy-token");if(!a)return false;const {data,error}=await sb.rpc("aria_autonomy_cron_authorize",{p_token:a});return !error&&data===true};
async function selectTextModel(capability:string){
 const {data,error}=await sb.from("aria_internal.capability_matrix").select("model_id").eq("capability_id",capability).eq("status","verified");if(error||!Array.isArray(data))return null;
 const candidates:any[]=[];
 for(const cap of data){const {data:model}=await sb.from("aria_internal.model_registry").select("model_id,provider_id,status,enabled,metadata").eq("model_id",cap.model_id).maybeSingle();if(!model||model.status!=="available"||model.enabled===false)continue;const {data:accounts}=await sb.from("aria_internal.account_registry").select("account_id,provider_id,status,enabled,models").eq("provider_id",model.provider_id).in("status",["active","available"]).eq("enabled",true);for(const account of(accounts??[])){const refs=Array.isArray(account.models)?account.models:[];if(refs.length&&!refs.includes(model.model_id))continue;const {data:quota}=await sb.from("aria_internal.quota_registry").select("status,usage_requests,usage_tokens_total,rate_limit_requests").eq("account_id",account.account_id).eq("model_id",model.model_id).maybeSingle();if(!quota||quota.status!=="available")continue;let score=50;const evidence=["model_available","quota_available"];if(String(model.metadata?.access_path??"")==="google_gemini_direct"){score+=10;evidence.push("direct_provider_path")}if(Number(quota.usage_requests??0)>0||Number(quota.usage_tokens_total??0)>0){score+=5;evidence.push("usage_observed")}const unknown=["cost","latency","risk_quality"];if(quota.rate_limit_requests==null)unknown.push("rate_limit");candidates.push({provider_id:model.provider_id,account_id:account.account_id,model_id:model.model_id,score,evidence,unknown_dimensions:unknown});}}
 candidates.sort((a,b)=>b.score-a.score||a.provider_id.localeCompare(b.provider_id)||a.account_id.localeCompare(b.account_id)||a.model_id.localeCompare(b.model_id));return candidates[0]??null;
}
Deno.serve(async r=>{if(r.method!=="POST")return out({error:"method_not_allowed"},405);if(!(await auth(r)))return out({error:"unauthorized"},401);const b=await r.json().catch(()=>({}));const goal=typeof b.goal==="string"?b.goal.trim():"";if(!goal)return out({error:"goal_required"},400);const context=b.context&&typeof b.context==="object"&&!Array.isArray(b.context)?b.context:{};const lower=goal.toLowerCase();const modelIntent=/\b(gemini|modelo|model|llm|ia|generar|texto)\b/.test(lower);if(modelIntent){const selected=await selectTextModel("text_generation");if(!selected)return out({error:"no_verified_text_model_route",planner_version:"aria-planner-v12-model-aware"},503);const step={id:"model_1",operation:"text_generation",executor_type:"model",capability:"text_generation",target:{type:"model",provider_id:selected.provider_id,account_id:selected.account_id,model_id:selected.model_id},input:{payload:{prompt:`ARIA task. Goal: ${goal}\nRespond briefly with the key result and never reveal secrets.`,max_tokens:256,temperature:0}},risk:"READ",timeout_ms:60000,policy:{},authorization:{status:"approved",risk_class:"READ",evidence_ref:"planner:evidence-router-v1.2"},verify:{},selection:{reason:"evidence_weighted_router_v1.2",score:selected.score,evidence:selected.evidence,unknown_dimensions:selected.unknown_dimensions}};return out({ok:true,plan:{goal,steps:[step],planner_version:"aria-planner-v1.2-model-aware",selected_route:selected,cognitive_context:context}});}try{const h:Record<string,string>={"content-type":"application/json"};const t=r.headers.get("x-aria-autonomy-token");if(t)h["x-aria-autonomy-token"]=t;else h.authorization=`Bearer ${SECRET}`;const upstream=await fetch(`${URL}/functions/v1/aria-planner-v10`,{method:"POST",headers:h,body:JSON.stringify({goal,context})});const p=await upstream.json().catch(()=>null);return out(p,upstream.status);}catch{return out({error:"planner_proxy_failed"},502)}});