const GH="https://api.github.com";
const te=new TextEncoder();
const b64u=(bytes)=>{let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")};
const fromB64=(s)=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
function derLen(n){if(n<128)return Uint8Array.of(n);const a=[];while(n){a.unshift(n&255);n>>>=8}return Uint8Array.of(0x80|a.length,...a)}
function derTag(tag,body){const l=derLen(body.length);const o=new Uint8Array(1+l.length+body.length);o[0]=tag;o.set(l,1);o.set(body,1+l.length);return o}
function derSeq(...parts){let n=0;for(const p of parts)n+=p.length;const b=new Uint8Array(n);let i=0;for(const p of parts){b.set(p,i);i+=p.length}return derTag(0x30,b)}
function derInt(bytes){let b=bytes[0]===0?bytes:Uint8Array.of(0,...bytes);return derTag(0x02,b)}
function pkcs1ToPkcs8(der){let i=0;const read=()=>{if(der[i++]!==0x30)throw Error("invalid_rsa_pkcs1");let n=der[i++];if(n&128){const k=n&127;n=0;for(let j=0;j<k;j++)n=n*256+der[i++]}const end=i+n;return[end]};const [end]=read();i=4;const ints=[];while(i<end){if(der[i++]!==2)throw Error("invalid_rsa_integer");let n=der[i++];if(n&128){const k=n&127;n=0;for(let j=0;j<k;j++)n=n*256+der[i++]}ints.push(der.subarray(i,i+n));i+=n}if(ints.length<9)throw Error("invalid_rsa_pkcs1_fields");const alg=derSeq(derTag(0x06,Uint8Array.of(0x2a,0x86,0x48,0x86,0xf7,0x0d,0x01,0x01,0x01)),derTag(0x05,new Uint8Array()));const inner=derSeq(...ints.map(derInt));return derSeq(derInt(Uint8Array.of(0)),alg,derTag(0x04,inner))}
function pemDer(pem){const clean=pem.replace(/-----BEGIN [^-]+-----|-----END [^-]+-----|\s/g,"");return fromB64(clean)}
async function appJwt(){const pem=Deno.env.get("ARIA_GITHUB_APP_PRIVATE_KEY")??"";if(!pem)throw Error("github_app_private_key_missing");const appId=Deno.env.get("ARIA_GITHUB_APP_ID")??"4835157";let der=pemDer(pem);if(pem.includes("BEGIN RSA PRIVATE KEY"))der=pkcs1ToPkcs8(der);const key=await crypto.subtle.importKey("pkcs8",der,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const now=Math.floor(Date.now()/1000);const head=b64u(te.encode(JSON.stringify({alg:"RS256",typ:"JWT"})));const body=b64u(te.encode(JSON.stringify({iat:now-60,exp:now+540,iss:appId})));const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,te.encode(`${head}.${body}`));return`${head}.${body}.${b64u(new Uint8Array(sig))}`}
async function gh(path,opts={}){const r=await fetch(`${GH}${path}`,{...opts,headers:{accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","user-agent":"ARIA-github-app-runtime-v1",...(opts.headers??{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(`github_${r.status}:${b?.message??"request_failed"}`);return b}
export async function githubInstallation(){const jwt=await appJwt();const installations=await gh("/app/installations",{headers:{authorization:`Bearer ${jwt}`}});const owner=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9";const wanted=Array.isArray(installations)?installations.find(x=>x.account?.login?.toLowerCase()===owner.toLowerCase()):null;if(!wanted)throw Error(`github_installation_not_found:${owner}`);return{id:wanted.id,account:wanted.account?.login??owner,repositories_url:wanted.repositories_url??null}}
async function installationToken(){const inst=await githubInstallation();const jwt=await appJwt();const b=await gh(`/app/installations/${inst.id}/access_tokens`,{method:"POST",headers:{authorization:`Bearer ${jwt}`},body:JSON.stringify({repositories:[Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker"]})});return{token:b.token,expires_at:b.expires_at,installation_id:inst.id,account:inst.account}}
function safePath(path){const p=String(path??"").replace(/^\/+/,"");if(!p||p.includes("..")||p.includes(".git/")||p.startsWith(".github/workflows/"))throw Error("github_path_not_allowed");return p}
export async function githubRead(path,ref="main"){const p=safePath(path);const t=await installationToken();const b=await gh(`/repos/${Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9"}/${Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker"}/contents/${p}?ref=${encodeURIComponent(ref)}`,{headers:{authorization:`Bearer ${t.token}`}});return{ok:true,status:200,executor_type:"connector",connector_id:"github",operation:"file_read",data:b,installation_id:t.installation_id,expires_at:t.expires_at}}
export async function githubWrite({path,content,branch,base="main",message}){const p=safePath(path);if(String(content??"").length>200000)throw Error("github_content_too_large");if(/(?:BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY|ghp_[A-Za-z0-9_\-]+|github_pat_[A-Za-z0-9_\-]+|sb_secret_[A-Za-z0-9_\-]+)/i.test(String(content)))throw Error("github_secret_material_rejected");if(!branch||/^(main|master)$/.test(branch))throw Error("github_write_branch_required");const t=await installationToken();const owner=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9",repo=Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker";let existing=null;try{existing=await gh(`/repos/${owner}/${repo}/contents/${p}?ref=${encodeURIComponent(branch)}`,{headers:{authorization:`Bearer ${t.token}`}})}catch(e){if(!String(e?.message??e).startsWith("github_404"))throw e}const payload={message:message??`ARIA autonomous write: ${p}`,content:b64u(te.encode(String(content))),branch};if(existing?.sha)payload.sha=existing.sha;const b=await gh(`/repos/${owner}/${repo}/contents/${p}`,{method:"PUT",headers:{authorization:`Bearer ${t.token}`,"content-type":"application/json"},body:JSON.stringify(payload)});return{ok:true,status:200,executor_type:"connector",connector_id:"github",operation:"file_write",branch,path:p,commit_sha:b.commit?.sha??null,content_sha:b.content?.sha??null,installation_id:t.installation_id,expires_at:t.expires_at}}
export async function githubCreateBranch({branch,base="main"}){if(!branch||/^(main|master)$/.test(branch))throw Error("github_write_branch_required");const t=await installationToken();const owner=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9",repo=Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker";const ref=await gh(`/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(base)}`,{headers:{authorization:`Bearer ${t.token}`}});const b=await gh(`/repos/${owner}/${repo}/git/refs`,{method:"POST",headers:{authorization:`Bearer ${t.token},","content-type":"application/json"},body:JSON.stringify({ref:`refs/heads/${branch}`,sha:ref.object.sha})});return{ok:true,status:201,executor_type:"connector",connector_id:"github",operation:"branch_create",branch,base,commit_sha:b.object?.sha??ref.object.sha,installation_id:t.installation_id,expires_at:t.expires_at}}
export async function githubPr({branch,base="main",title,body,draft=false}){if(!branch||/^(main|master)$/.test(branch))throw Error("github_write_branch_required");const t=await installationToken();const owner=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9",repo=Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker";const b=await gh(`/repos/${owner}/${repo}/pulls`,{method:"POST",headers:{authorization:`Bearer ${t.token},","content-type":"application/json"},body:JSON.stringify({title:title??"ARIA autonomous change",head:branch,base,body:body??"Automated change proposed by ARIA. Human review required before merge.",draft})});return{ok:true,status:201,executor_type:"connector",connector_id:"github",operation:"pull_request_create",number:b.number,url:b.html_url,branch,base,installation_id:t.installation_id,expires_at:t.expires_at}}
export async function githubAppHealth(){const i=await githubInstallation();return{ok:true,status:200,executor_type:"connector",connector_id:"github",operation:"health",installation_id:i.id,account:i.account}}
