const GH="https://api.github.com";
const te=new TextEncoder();
const b64u=(bytes)=>{let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")};
const b64=(bytes)=>{let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)};
const fromB64=(s)=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
function readTlv(a,pos){let i=pos;if(a[i++]!==0x30)throw Error("invalid_rsa_sequence");let n=a[i++];if(n&128){const k=n&127;n=0;for(let j=0;j<k;j++)n=n*256+a[i++]}return{bodyStart:i,end:i+n}}
function pkcs1ToPkcs8(a){const q=readTlv(a,0),ints=[];let i=q.bodyStart;while(i<q.end){if(a[i++]!==2)throw Error("invalid_rsa_integer");let n=a[i++];if(n&128){const k=n&127;n=0;for(let j=0;j<k;j++)n=n*256+a[i++]}ints.push(a.slice(i,i+n));i+=n}if(ints.length<9)throw Error("invalid_rsa_pkcs1_fields");const tag=(t,b)=>{const l=b.length;if(l<128)return Uint8Array.of(t,l,...b);const z=[];let x=l;while(x){z.unshift(x&255);x>>>=8}return Uint8Array.of(t,0x80|z.length,...z,...b)};const seq=(...p)=>tag(0x30,p.reduce((a,x)=>Uint8Array.of(...a,...x),new Uint8Array()));const integer=x=>tag(2,x[0]===0?x:Uint8Array.of(0,...x));const alg=seq(tag(6,Uint8Array.of(0x2a,0x86,0x48,0x86,0xf7,0x0d,1,1,1)),tag(5,new Uint8Array()));return seq(integer(Uint8Array.of(0)),alg,tag(4,seq(...ints.map(integer))))}
function pemDer(pem){const s=pem.replace(/-----BEGIN [^-]+-----|-----END [^-]+-----|\s/g,"");return fromB64(s)}
async function appJwt(){const pem=Deno.env.get("ARIA_GITHUB_APP_PRIVATE_KEY")??"";if(!pem)throw Error("github_app_private_key_missing");const appId=Deno.env.get("ARIA_GITHUB_APP_ID")??"4835157";let der=pemDer(pem);if(pem.includes("BEGIN RSA PRIVATE KEY"))der=pkcs1ToPkcs8(der);const key=await crypto.subtle.importKey("pkcs8",der,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const now=Math.floor(Date.now()/1000),h=b64u(te.encode(JSON.stringify({alg:"RS256",typ:"JWT"}))),p=b64u(te.encode(JSON.stringify({iat:now-60,exp:now+540,iss:appId}))),sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,te.encode(`${h}.${p}`));return`${h}.${p}.${b64u(new Uint8Array(sig))}`}
async function gh(path,opts={}){const r=await fetch(`${GH}${path}`,{...opts,headers:{accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","user-agent":"ARIA-github-app-runtime-v1",...(opts.headers??{})}}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(`github_${r.status}:${b?.message??"request_failed"}`);return b}
export async function githubInstallation(){const jwt=await appJwt(),list=await gh("/app/installations",{headers:{authorization:`Bearer ${jwt}`}}),owner=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9",wanted=Array.isArray(list)?list.find(x=>x.account?.login?.toLowerCase()===owner.toLowerCase()):null;if(!wanted)throw Error(`github_installation_not_found:${owner}`);return{id:wanted.id,account:wanted.account?.login??owner}}
async function installationToken(){const i=await githubInstallation(),jwt=await appJwt(),b=await gh(`/app/installations/${i.id}/access_tokens`,{method:"POST",headers:{authorization:`Bearer ${jwt}`,"content-type":"application/json"},body:JSON.stringify({repositories:[Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker"]})});return{token:b.token,expires_at:b.expires_at,installation_id:i.id,account:i.account}}
function safePath(path){const p=String(path??"").replace(/^\/+/,"");if(!p||p.includes("..")||p.includes(".git/")||p.startsWith(".github/workflows/"))throw Error("github_path_not_allowed");return p}
export async function githubRead(path,ref="main"){const p=safePath(path),t=await installationToken(),b=await gh(`/repos/${Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9"}/${Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker"}/contents/${p}?ref=${encodeURIComponent(ref)}`,{headers:{authorization:`Bearer ${t.token}`}});return{ok:true,status:200,executor_type:"connector",connector_id:"github",operation:"file_read",data:b,installation_id:t.installation_id,expires_at:t.expires_at}}
export async function githubCreateBranch({branch,base="main"}){if(!branch||/^(main|master)$/.test(branch))throw Error("github_write_branch_required");const t=await installationToken(),o=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9",r=Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker",ref=await gh(`/repos/${o}/${r}/git/ref/heads/${encodeURIComponent(base)}`,{headers:{authorization:`Bearer ${t.token}`}}),b=await gh(`/repos/${o}/${r}/git/refs`,{method:"POST",headers:{authorization:`Bearer ${t.token}`,"content-type":"application/json"},body:JSON.stringify({ref:`refs/heads/${branch}`,sha:ref.object.sha})});return{ok:true,status:201,executor_type:"connector",connector_id:"github",operation:"branch_create",branch,base,commit_sha:b.object?.sha??ref.object.sha,installation_id:t.installation_id,expires_at:t.expires_at}}
export async function githubWrite({path,content,branch,message,base="main"}){const p=safePath(path),body=String(content??"");if(body.length>200000)throw Error("github_content_too_large");if(/(?:BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY|ghp_[A-Za-z0-9_-]+|github_pat_[A-Za-z0-9_-]+|sb_secret_[A-Za-z0-9_-]+)/i.test(body))throw Error("github_secret_material_rejected");if(!branch||/^(main|master)$/.test(branch))throw Error("github_write_branch_required");const t=await installationToken(),o=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9",r=Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker";let existing=null;try{existing=await gh(`/repos/${o}/${r}/contents/${p}?ref=${encodeURIComponent(branch)}`,{headers:{authorization:`Bearer ${t.token}`}})}catch(e){if(!String(e?.message??e).startsWith("github_404"))throw e}const payload={message:message??`ARIA autonomous write: ${p}`,content:b64(te.encode(body)),branch};if(existing?.sha)payload.sha=existing.sha;const b=await gh(`/repos/${o}/${r}/contents/${p}`,{method:"PUT",headers:{authorization:`Bearer ${t.token}`,"content-type":"application/json"},body:JSON.stringify(payload)});return{ok:true,status:200,executor_type:"connector",connector_id:"github",operation:"file_write",branch,path:p,base,commit_sha:b.commit?.sha??null,content_sha:b.content?.sha??null,installation_id:t.installation_id,expires_at:t.expires_at}}
export async function githubPr({branch,base="main",title,body,draft=false}){if(!branch||/^(main|master)$/.test(branch))throw Error("github_write_branch_required");const t=await installationToken(),o=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9",r=Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker",b=await gh(`/repos/${o}/${r}/pulls`,{method:"POST",headers:{authorization:`Bearer ${t.token}`,"content-type":"application/json"},body:JSON.stringify({title:title??"ARIA autonomous change",head:branch,base,body:body??"Automated change proposed by ARIA. Human review required before merge.",draft})});return{ok:true,status:201,executor_type:"connector",connector_id:"github",operation:"pull_request_create",number:b.number,url:b.html_url,branch,base,installation_id:t.installation_id,expires_at:t.expires_at}}
export async function githubAppHealth(){const i=await githubInstallation();return{ok:true,status:200,executor_type:"connector",connector_id:"github",operation:"health",installation_id:i.id,account:i.account}}
