import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,SECRET=Deno.env.get("ARIA_RUNTIME_SHARED_SECRET")!;
const INTAKE=`${URL}/functions/v1/aria-mission-intake-v1`,RUNNER=`${URL}/functions/v1/aria-mission-runner-v6`,GATEWAY=`${URL}/functions/v1/aria-device-gateway`;
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const eq=(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0};
const bearer=(r:Request)=>{const h=r.headers.get("authorization")??"";return h.startsWith("Bearer ")?h.slice(7):null};
async function rpc(n:string,a:Record<string,unknown>){const {data,error}=await sb.rpc(n,a);if(error)throw new Error(`${n}:${error.message}`);return data}
async function authorized(r:Request){const t=bearer(r);if(t&&SECRET&&eq(t,SECRET))return true;const c=r.headers.get("x-aria-autonomy-token");return c?Boolean(await rpc("aria_autonomy_cron_authorize",{p_token:c})):false}
async function scan(){const {data:goals,error}=await sb.schema("aria_internal").from("autonomy_goals").select("goal_id,goal,priority,status,next_run_at,attempts,max_attempts,last_mission_id,updated_at").order("priority",{ascending:true});if(error)throw new Error(`goals:${error.message}`);const {data:missions,error:me}=await sb.schema("aria_internal").from("mission_state").select("mission_id,status,updated_at,finished_at").in("status",["queued","planning","running"]);if(me)throw new Error(`missions:${me.message}`);return {goals:Array.isArray(goals)?goals:[],active:Array.isArray(missions)?missions:[]}}
async function reconcile(goals:any[]){for(const g of goals){if(!g.last_mission_id||g.status!=="running")continue;const {data,error}=await sb.schema("aria_internal").from("mission_state").select("status,finished_at,last_stderr").eq("mission_id",g.last_mission_id).maybeSingle();if(error||!data)continue;if(data.status==="succeeded"){await sb.schema("aria_internal").from("autonomy_goals").update({status:"completed",updated_at:new Date().toISOString()}).eq("goal_id",g.goal_id)}else if(data.status==="blocked"){const next=(Number(g.attempts)||0)+1;await sb.schema("aria_internal").from("autonomy_goals").update({status:next<(Number(g.max_attempts)||3)?"queued":"blocked",attempts:next,next_run_at:new Date(Date.now()+Math.min(next*5,30)*60000).toISOString(),updated_at:new Date().toISOString()}).eq("goal_id",g.goal_id)}}}
function planFor(id:string){const s=(op:string,c:string,input:any)=>({id:`${id}_${op}`,operation:op,executor_type:"connector",target:{type:"connector",connector_id:c,device_id:null},input,risk:"READ",cwd:null,timeout_ms:30000});if(id==="autonomy-health")return [s("account_read","cloudflare",{script_name:"aria"}),s("worker_read","cloudflare",{script_name:"aria"}),s("file_read","github",{owner:"Robvg9",repo:"aria-worker",path:"worker.js",ref:"main"})];if(id==="autonomy-worker-audit")return [s("file_read","github",{owner:"Robvg9",repo:"aria-worker",path:"worker.js",ref:"main"}),s("content_read","cloudflare",{script_name:"aria"})];if(id==="autonomy-tests")return [s("file_read","github",{owner:"Robvg9",repo:"aria-worker",path:"package.json",ref:"main"}),s("repo_read","github",{owner:"Robvg9",repo:"aria-worker"})];if(id==="autonomy-docs")return [s("file_read","github",{owner:"Robvg9",repo:"aria-worker",path:"README.md",ref:"main"})];if(id==="autonomy-self-review")return [s("repo_read","github",{owner:"Robvg9",repo:"aria-worker"}),s("account_read","cloudflare",{script_name:"aria"})];return null}
async function createMission(g:any){const checkpoint=planFor(g.goal_id);const r=await fetch(INTAKE,{method:"POST",headers:{authorization:`Bearer ${SECRET}`,"content-type":"application/json"},body:JSON.stringify({goal:g.goal,checkpoint:checkpoint?{plan:checkpoint}:undefined,metadata:{source:"autonomy_goal_manager_v2",goal_id:g.goal_id,policy:"safe-progress-v2",human_gate_required:["HIGH_RISK_WRITE","destructive","production_merge"]}})});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(`intake:${r.status}`);const id=j.mission?.mission_id;await sb.schema("aria_internal").from("autonomy_goals").update({status:"running",last_mission_id:id,attempts:(Number(g.attempts)||0)+1,updated_at:new Date().toISOString()}).eq("goal_id",g.goal_id);return id}
async function kick(){const r=await fetch(`${GATEWAY}/v1/autonomy/cycle`,{method:"POST",headers:{authorization:`Bearer ${SECRET}`,"content-type":"application/json"},body:JSON.stringify({trigger:"autonomy-supervisor-v5"})});return await r.json().catch(()=>({status:r.status}))}
Deno.serve(async r=>{if(r.method!=="POST")return out({error:"method_not_allowed"},405);try{if(!await authorized(r))return out({error:"unauthorized"},401);const a=await scan();await reconcile(a.goals);const b=await scan();let created=null;if(b.active.length===0){const g=b.goals.find(x=>x.status==="queued"&&Date.parse(x.next_run_at)<=Date.now());if(g)created=await createMission(g)}const runtime=await kick();return out({ok:true,active_before:a.active.length,mission_created:created,runtime})}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},200)}});
