'use strict';
const assert=require('node:assert/strict');
const {VERSION,canonical,sha256,fingerprint}=require('../fingerprint-v1');
const core=require('../engine-v1');
const trend=require('../trend-v1');
const fs=require('node:fs');
const crypto=require('node:crypto');
const dbDigest=fs.readFileSync(require.resolve('../../supabase/migrations/20261004041000_proactive_fingerprint_digest_sha256_v1.sql'),'utf8');
const dbTrend=fs.readFileSync(require.resolve('../../supabase/migrations/20261004041500_proactive_fingerprint_trend_sha256_v1.sql'),'utf8');
const dbVerify=fs.readFileSync(require.resolve('../../supabase/migrations/20261004042000_proactive_digest_verify_algorithm_v1.sql'),'utf8');
const liveProof=fs.readFileSync(require.resolve('../../.github/workflows/proactive-signal-quality-live-proof.yml'),'utf8');
assert.equal(VERSION,'aria-proactive-fingerprint-v1.0.0');
assert.equal(sha256({a:1,b:2}),sha256({b:2,a:1}));
assert.equal(fingerprint({hello:'world'}),crypto.createHash('sha256').update(canonical({hello:'world'})).digest('hex'));
assert.equal(core.sha256({x:1}),sha256({x:1}));
assert.equal(trend.sha256({x:1}),sha256({x:1}));
const coreSource=require('node:fs').readFileSync(require.resolve('../engine-v1'),'utf8');
const trendSource=require('node:fs').readFileSync(require.resolve('../trend-v1'),'utf8');
assert.doesNotMatch(coreSource,/node:crypto/);
assert.doesNotMatch(trendSource,/node:crypto/);
assert.doesNotMatch(coreSource,/md5/i);
assert.doesNotMatch(trendSource,/md5/i);
assert.match(dbDigest,/fingerprint_algorithm.*'sha256'/s);
assert.match(dbDigest,/sha256/);
assert.match(dbTrend,/fingerprint_algorithm.*'sha256'/s);
assert.match(dbTrend,/sha256/);
assert.match(dbVerify,/fingerprint_algorithm/);
assert.match(liveProof,/refresh_proactive_digest_v1/);
assert.match(liveProof,/verify_proactive_digest_v1/);
assert.match(liveProof,/refresh_proactive_trends_v1/);
assert.match(liveProof,/verify_proactive_trends_v1/);
assert.match(liveProof,/paths:/);
assert.doesNotMatch(liveProof,/mission|execution_job|meditation_queue/i);
console.log('PROACTIVE SIGNAL QUALITY V1: PASS — shared canonical SHA-256 utility, consistent Core/Trend identity, legacy hashes remain explicit');
