'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const engine=fs.readFileSync(require.resolve('../trend-v1'),'utf8');
const contract=fs.readFileSync(require.resolve('../trend-contract-v1.md'),'utf8');
const table=fs.readFileSync(require.resolve('../../supabase/migrations/20261004033000_proactive_trends_v1.sql'),'utf8');
const refresh=fs.readFileSync(require.resolve('../../supabase/migrations/20261004033500_proactive_trends_refresh_v1.sql'),'utf8');
const verify=fs.readFileSync(require.resolve('../../supabase/migrations/20261004034000_proactive_trends_verify_v1.sql'),'utf8');
assert.match(engine,/recommendation_only/);
assert.match(engine,/persistent/);
assert.match(engine,/recurring/);
assert.doesNotMatch(engine,/enqueue_execution_job|claim_execution_job|runner_tick_for_mission|meditation_queue_add/);
assert.match(contract,/recommendation_only/);
assert.match(table,/enable row level security/);
assert.match(table,/service_role/);
assert.match(refresh,/refresh_proactive_trends_v1/);
assert.match(refresh,/proactive_digests/);
assert.match(refresh,/occ >= 3|occ>=3/);
assert.match(refresh,/occ = 2|occ=2/);
assert.doesNotMatch(refresh,/mission_state|execution_jobs|meditation/i);
assert.match(verify,/verify_proactive_trends_v1/);
console.log('PROACTIVE TREND LIVE CONTRACT: PASS — deterministic history analytics, recurrence/persistence, protected storage, no actuation');
