'use strict';
const assert=require('node:assert/strict');
const {VERSION,ACTION_MODE,auditProactiveConsistency}=require('../consistency-auditor-v1');
const fs=require('node:fs');
const sql=fs.readFileSync(require.resolve('../../supabase/migrations/20261004043000_proactive_consistency_auditor_v1.sql'),'utf8');
assert.equal(VERSION,'aria-proactive-consistency-auditor-v1.0.0');
assert.equal(ACTION_MODE,'recommendation_only');
const digest={digest_id:'d1',observed_at:'2026-10-04T07:00:00Z',recommendations:[]};
const mismatch={trend_id:'t1',trend_count:1,persistent_count:0,recurring_count:1,new_count:0,trends:[{trend_id:'tr1',state:'recurring',occurrence_count:1,digest_ids:['d1']}]};
const a=auditProactiveConsistency({digests:[digest],trends:[mismatch]});
assert.equal(a.status,'drift');
assert.ok(a.findings.some(f=>f.code==='trend_summary_mismatch'));
const missing=auditProactiveConsistency({digests:[],trends:[{trend_id:'t1',trend_count:1,persistent_count:0,recurring_count:1,new_count:0,trends:[{trend_id:'tr1',state:'recurring',occurrence_count:1,digest_ids:['missing']}]}]});
assert.ok(missing.findings.some(f=>f.code==='trend_source_missing'));
const clean=auditProactiveConsistency({digests:[digest],trends:[{trend_id:'t2',trend_count:1,persistent_count:0,recurring_count:0,new_count:1,trends:[{trend_id:'tr2',state:'new',occurrence_count:1,digest_ids:['d1']}]}]});
assert.equal(clean.status,'consistent');
assert.equal(Object.isFrozen(clean),true);
assert.match(sql,/audit_proactive_consistency_v1/);
assert.match(sql,/read_only/);
assert.doesNotMatch(sql,/insert into|update |delete from/i);
assert.match(sql,/proactive_digests/);
assert.match(sql,/proactive_trends/);
console.log('PROACTIVE CONSISTENCY AUDITOR V1: PASS — digest/trend counters, source references, drift detection and read-only LIVE contract');
