'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const refresh=fs.readFileSync(require.resolve('../../supabase/migrations/20261004031000_proactive_live_refresh_v1.sql'),'utf8');
const table=fs.readFileSync(require.resolve('../../supabase/migrations/20261004030000_proactive_digests_v1.sql'),'utf8');
const verify=fs.readFileSync(require.resolve('../../supabase/migrations/20261004031500_proactive_live_verify_v1.sql'),'utf8');
assert.match(refresh,/refresh_proactive_digest_v1/);
assert.match(refresh,/get_operational_health_v1/);
assert.match(refresh,/router_live_snapshot/);
assert.match(refresh,/recommendation_only/);
assert.match(refresh,/proactive_digests/);
assert.match(refresh,/security definer/i);
assert.doesNotMatch(refresh,/mission_state|execution_jobs|meditation/i);
assert.match(table,/enable row level security/);
assert.match(table,/grant select, insert on aria_internal\.proactive_digests to service_role/);
assert.match(verify,/verify_proactive_digest_v1/);
console.log('PROACTIVE LIVE V1 CONTRACT: PASS — protected SQL refresh, persistent digest, no mission coupling');
