'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const file = path.join(__dirname, '..', 'supabase', 'functions', 'aria-agent-runtime-v1', 'index.ts');
const loopFile = path.join(__dirname, '..', 'supabase', 'functions', 'aria-agent-runtime-v1', 'tool-loop.ts');
const source = fs.readFileSync(file, 'utf8');
const loopSource = fs.readFileSync(loopFile, 'utf8');

assert.match(source, /aria-agent-planner-v1/);
assert.match(source, /aria-agent-reviewer-v1/);
assert.match(source, /aria-agent-research-v1/);
assert.match(source, /aria-agent-coding-v1/);
assert.match(source, /aria-agent-security-v1/);
assert.match(source, /aria-agent-memory-v1/);
assert.match(source, /aria-agent-business-v1/);
assert.match(source, /aria-agent-device-v1/);
assert.match(source, /operation.*delegate/);
assert.match(source, /mutating_operation_required/, 'agent runtime must honor mutation policy');
assert.match(source, /LOW_RISK_WRITE/, 'LOW_RISK_WRITE must activate governed repair mode');
assert.match(source, /executor_type.*agent/);
assert.match(source, /aria-execution-runtime-v1/);
assert.match(source, /const requestId = `agent:/);
assert.match(source, /request_id:\s*requestId/);
assert.match(source, /authorization/);
assert.match(source, /risk_class/);
assert.match(source, /aria_agent_catalog/);
assert.match(source, /agent_unavailable_or_not_cataloged/);
assert.match(source, /prompt_missing/);
assert.doesNotMatch(source, /OPENAI_API_KEY|GOOGLE_API_KEY|GROK_API_KEY|sk-[A-Za-z0-9]{10,}/);
assert.doesNotMatch(source, /console\.log\s*\(.*SECRET/);
assert.match(loopSource, /max_completion_tokens:4000/, "coding agent tool loop must retain the governed 4000-token implementation budget");
assert.match(loopSource, /service_tier:\s*"flex"/);
assert.match(loopSource, /resolveToolRoute/, 'tool loop must resolve a provider/model tool route');
assert.match(loopSource, /callGeminiModel/, 'tool loop must support Google Gemini direct function calling');
assert.match(loopSource, /functionDeclarations/, 'Gemini tool declarations missing');
assert.match(loopSource, /functionCallingConfig/, 'Gemini function calling config missing');
assert.match(loopSource, /geminiParts/, 'Gemini response parts must be preserved for thought signatures');
assert.match(loopSource, /geminiParts/, 'Gemini response parts must be preserved verbatim across tool turns (including provider thought signatures when present)');
assert.match(loopSource, /gemini-3.5-flash-direct/, 'agent runtime must have a verified Google free-model fallback order');
assert.match(loopSource, /gemini-3.1-flash-lite-direct/, 'agent runtime must include a second Google free-model fallback');
assert.match(loopSource, /github_file_patch/, 'coding agent must have a governed targeted patch tool');
assert.ok(loopSource.includes('inspect pwa/src/App.tsx'), 'UI implementation prompt must require PWA source inspection');
assert.match(loopSource, /Do NOT return NO_CHANGE_REQUIRED/, 'implementation missions must not silently downgrade to read-only analysis');
assert.match(loopSource, /max_completion_tokens:4000/, 'coding agent needs sufficient output for tool-driven implementation');
assert.match(loopSource, /patch_match_count_/, 'targeted patch must fail closed on non-unique matches');
assert.doesNotMatch(loopSource, /preferred\.startsWith\("google\/"/, 'exhausted Google catalog preference must not bypass fallback ordering');
assert.match(loopSource, /GOOGLE_API_KEY/, 'Google Gemini credential path missing');
assert.match(loopSource, /eq\("provider_id","openrouter"\)/, 'tool model resolution must use the OpenRouter provider registry');
assert.match(loopSource, /endsWith\(":free"\)/, 'tool model resolution must stay on free verified models');
assert.match(loopSource, /preferredProvider/);
assert.doesNotMatch(loopSource, /recoveryAgentId\.includes\("-openrouter-"\)/, "agent IDs must not force an OpenRouter route when the catalog provider is Google");
assert.match(loopSource, /preferredProvider === "openrouter"/);

assert.match(loopSource, /providerLock/);
assert.match(loopSource, /recoveryOpenRouterOnly/);
assert.match(loopSource, /if \(providerLock && preferredProvider === "google"\) return routes\.slice\(0,8\)/);
assert.match(loopSource, /preferredIsFreeOpenRouter/);
assert.match(loopSource, /recoveryFreeOnly/);
assert.match(loopSource, /recovery_openrouter_free_route_unavailable/);
assert.match(loopSource, /recovery_google_route_forbidden/);
assert.match(loopSource, /provider: candidate\?\.provider/);
assert.match(loopSource, /recovery_free_only: isRecoveryFreeAgent/);
assert.match(loopSource, /free_route/);

assert.match(loopSource, /todavía no se ha producido ninguna escritura gobernada/);
assert.match(loopSource, /FINDINGS:/);
assert.match(loopSource, /CONFIRMED: la mutación quedó registrada/);
assert.match(source, /aria-agent-android-coding-openrouter-v1/);
assert.match(loopSource, /code|coder|coding/, 'tool model resolution must prefer coding-capable model names when available');
assert.doesNotMatch(loopSource, /\bmax_tokens:\s*3000/);

console.log('AGENT RUNTIME V1 CONTRACT: PASS');
