const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=process.cwd();
const v5=fs.readFileSync(path.join(root,"supabase/functions/aria-autonomy-supervisor-v5/index.ts"),"utf8");
const v10=fs.readFileSync(path.join(root,"supabase/functions/aria-autonomy-supervisor-v10/index.ts"),"utf8");
const migration=fs.readFileSync(path.join(root,"supabase/migrations/20260918170000_all_for_one_forensic_audit_v1.sql"),"utf8");
assert.match(v5,/aria-device-gateway/);
assert.match(v5,/\/v1\/autonomy\/cycle/);
assert.doesNotMatch(v5,/aria-mission-intake-v1/);
assert.doesNotMatch(v5,/aria-mission-runner-v6/);
assert.doesNotMatch(v5,/async function createMission/);
assert.doesNotMatch(v5,/generateCandidates/);
assert.match(v10,/aria-autonomy-supervisor-v5/);
assert.match(v10,/deprecated:true/);
assert.doesNotMatch(v10,/generateCandidates/);
assert.match(migration,/revoke execute on function aria_internal\.run_mission_runner_tick_v1\(\)/i);
assert.match(migration,/alter function aria_internal\.canonical_vision_goal_id\(p_objective_id text\) set search_path/i);
assert.match(migration,/alter table aria_internal\.goal_audit_snapshots_v1 add constraint/i);
assert.match(migration,/create index if not exists .*execution_jobs_device_id_idx/i);
assert.match(migration,/aria-autonomy-supervisor-v5/);
console.log("ALL FOR ONE FORENSIC AUDIT CONTRACT: PASS");
