const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=process.cwd();
const v5=fs.readFileSync(path.join(root,"supabase/functions/aria-autonomy-supervisor-v5/index.ts"),"utf8");
const v10=fs.readFileSync(path.join(root,"supabase/functions/aria-autonomy-supervisor-v10/index.ts"),"utf8");
const migration=fs.readFileSync(path.join(root,"supabase/migrations/20260918170000_all_for_one_forensic_audit_v1.sql"),"utf8");
const gateway=fs.readFileSync(path.join(root,"supabase/functions/aria-device-gateway/index.ts"),"utf8");
assert.match(v5,/aria-device-gateway/);
assert.match(v5,/\/v1\/autonomy\/cycle/);
assert.doesNotMatch(v5,/aria-mission-intake-v1/);
assert.doesNotMatch(v5,/aria-mission-runner-v6/);
assert.doesNotMatch(v5,/async function createMission/);
assert.doesNotMatch(v5,/generateCandidates/);assert.match(gateway,/classifyAllForOneProviderBlock/);
assert.match(gateway,/free-models-per-day/);
assert.match(gateway,/currently experiencing high demand/);
assert.match(gateway,/blocked_provider/);
assert.match(gateway,/const auditorStatus=out\.status===.blocked./);
assert.match(gateway,/coverage\.first_pass\.failed===0/);
assert.match(v10,/aria-autonomy-supervisor-v5/);
assert.match(v10,/deprecated:true/);
assert.doesNotMatch(v10,/generateCandidates/);
assert.match(migration,/revoke execute on function aria_internal\.run_mission_runner_tick_v1\(\)/i);
assert.match(migration,/alter function aria_internal\.canonical_vision_goal_id\(p_objective_id text\) set search_path/i);
assert.match(migration,/alter table aria_internal\.goal_audit_snapshots_v1\s+add constraint/i);
assert.match(migration,/create index if not exists .*execution_jobs_device_id_idx/i);
assert.match(migration,/v10 compatibility shim -> v5 -> Gateway/);
console.log("ALL FOR ONE FORENSIC AUDIT CONTRACT: PASS");

const emergency=fs.readFileSync(path.join(root,".github/workflows/aria-windows-emergency-repair.yml"),"utf8");
assert.match(emergency,/aria-approved-repair/);
assert.match(emergency,/github\.event\.issue\.user\.login == 'Robvg9'/);
assert.doesNotMatch(emergency,/git push origin main/);
assert.match(emergency,/gh pr create --draft/);

const appWorkflow=fs.readFileSync(path.join(root,".github/workflows/aria-app-api-deploy.yml"),"utf8");
assert.doesNotMatch(appWorkflow,/--verify-jwt/);
assert.match(appWorkflow,/supabase functions deploy aria-app-api-v1/);
const cloudflareWorkflow=fs.readFileSync(path.join(root,".github/workflows/aria-cloudflare-deploy.yml"),"utf8");
assert.doesNotMatch(cloudflareWorkflow,/Apply Grok embedded-browser consent compatibility patch/);
assert.match(cloudflareWorkflow,/x-aria-grok-consent/);
const forbiddenSelfPatcher=path.join(root,".github/workflows/fix-grok-consent-compat.yml");
assert.equal(fs.existsSync(forbiddenSelfPatcher),false);

const windowsQwen3=fs.readFileSync(path.join(root,".github/workflows/aria-autonomous-windows-qwen3.yml"),"utf8");
assert.match(windowsQwen3,/windows-qwen3/);
assert.match(windowsQwen3,/ARIA_SELF_MODEL_SKILL_E2E_OK|AUTONOMOUS_WINDOWS_QWEN3/);
assert.equal(fs.existsSync(path.join(root,".github/workflows/aria-windows-shell-live.yml")),false);
assert.equal(fs.existsSync(path.join(root,".github/workflows/aria-windows-shell-live-v2.yml")),false);
assert.equal(fs.existsSync(path.join(root,".github/workflows/aria-windows-direct-repair.yml")),false);