'use strict';
const assert=require('node:assert/strict');
const {createPlatformRegistry}=require('../platform/registry');
const {validateExtensionContract}=require('../platform/contract');
const {transition}=require('../platform/lifecycle');
const {createTool,createAgent,createConnector}=require('../platform/factories');
const {discover,capabilities}=require('../platform/discovery');
const {createMarketplace}=require('../platform/marketplace');
const {createScheduler}=require('../platform/scheduler');
const {createMaintenance}=require('../platform/maintenance');
const {createPlatformCoordinator}=require('../platform/coordinator');
(async()=>{
 const r=createPlatformRegistry();
 assert.equal(validateExtensionContract({id:'tool-x',type:'tool',version:'1.0.0'}).valid,true);
 assert.equal(validateExtensionContract({id:'tool-x',type:'bad',version:'1.0.0'}).valid,false);
 assert.equal(createTool({id:'tool-x',name:'Tool X',version:'1.0.0',status:'available',capabilities:['x']},r).ok,true);
 assert.equal(createAgent({id:'agent-x',name:'Agent X',version:'1.0.0',status:'available',capabilities:['research']},r).ok,true);
 assert.equal(createConnector({id:'conn-x',name:'Conn X',version:'1.0.0',status:'inactive',capabilities:['x']},r).ok,true);
 assert.equal(discover(r,{capability:'research'}).length,1);
 assert.deepEqual(capabilities(r),['research','x']);
 const activeTransition=transition(r.get('conn-x'),'active'); assert.equal(activeTransition.ok,true);
 assert.equal(transition({...r.get('conn-x'),status:'active'},'removed').ok,false);
 const m=createMarketplace(r); assert.equal(m.publish(r.get('tool-x'),{verified:false}).ok,false); assert.equal(m.publish(r.get('tool-x'),{verified:true}).ok,true); assert.equal(m.list().length,1);
 const s=createScheduler(); assert.equal(s.schedule({id:'job-1',due_at:10,task_id:'t1'}).ok,true); assert.equal(s.due(9).length,0); assert.equal(s.due(10).length,1); assert.equal(s.cancel('job-1'),true); assert.equal(s.due(10).length,0);
 const maintenance=createMaintenance({inspect:async()=>({healthy:false}),repair:async()=>({fixed:true}),test:async()=>true,document:async()=>({written:true})});
 const mr=await maintenance.run({}); assert.equal(mr.status,'verified');
 const pc=createPlatformCoordinator({registry:r,lifecycle:{transition},marketplace:m,scheduler:s}); assert.equal(pc.inspect().items.length,3); assert.equal(pc.publish('agent-x',{verified:true}).ok,true);
 assert.equal(createTool({id:'secret-tool',name:'x',version:'1.0.0',metadata:{api_key:'x'}},r).ok,false);
 console.log('BLOCK 9 PLATFORM TESTS PASS');
})();