/** Mission 10.7 — Fallback current contract tests */
const assert=require('assert');
const {resolve,candidateKey,candidateSelectable,activationAllows,version,registry}=require('../fallback/lookup.js');
const router=require('../router/lookup.js');
const model=require('../models/lookup.js');
const cap=require('../capabilities/lookup.js');
const account=require('../accounts/lookup.js');
const quota=require('../quota/lookup.js');
let n=0;const ok=(c,m)=>{assert.ok(c,m);n++;console.log('PASS:',m)};
const CAP='text_generation',A={provider_id:'openrouter',account_id:'acct_openrouter_primary',model_id:'google/gemini-2.5-flash-lite'},B={provider_id:'provider_b',account_id:'acct_b',model_id:'model_b'},C={provider_id:'provider_c',account_id:'acct_c',model_id:'model_c'};
const selected=c=>({status:'selected',...c,capability:CAP});
const deps=(over={})=>{const cfg={accounts:{[A.account_id]:{status:'active',credential_ref:'secret://openrouter/acct_openrouter_primary',provider_id:A.provider_id},[B.account_id]:{status:'active',credential_ref:'secret://provider_b/acct_b',provider_id:B.provider_id},[C.account_id]:{status:'active',credential_ref:'secret://provider_c/acct_c',provider_id:C.provider_id}},models:{[A.model_id]:{model_id:A.model_id,provider_id:A.provider_id,status:'available'},[B.model_id]:{model_id:B.model_id,provider_id:B.provider_id,status:'available'},[C.model_id]:{model_id:C.model_id,provider_id:C.provider_id,status:'available'}},supportsMap:{[A.model_id+'|'+CAP]:true,[B.model_id+'|'+CAP]:true,[C.model_id+'|'+CAP]:true},quota:{[A.account_id+'|'+A.model_id]:{capacity:'available',quota:'available',rate_limit:'available'},[B.account_id+'|'+B.model_id]:{capacity:'available',quota:'available',rate_limit:'available'},[C.account_id+'|'+C.model_id]:{capacity:'available',quota:'available',rate_limit:'available'}},candidates:[A,B,C],...over};const capacityAllows=(id,m)=>{const q=cfg.quota[id+'|'+m];return !!q&&q.capacity==='available'&&q.quota==='available'&&q.rate_limit!=='unavailable'&&q.rate_limit!=='exhausted'&&q.rate_limit!=='unknown'};return{route:()=>selected(A),collectCandidates:()=>cfg.candidates.slice(),capacityAllows,isAccountActive:id=>cfg.accounts[id]?.status==='active',supports:(m,c)=>cfg.supportsMap[m+'|'+c]===true,getModel:id=>cfg.models[id]||null,credentialRefOf:id=>cfg.accounts[id]?.credential_ref||null}};
console.log('=== Fallback current contract ===');
ok(version==='aria-fallback-v1.0.0','fallback version current');
ok(registry.canonical_status.join(',')==='primary,fallback,no_fallback','canonical fallback states');
ok(resolve({router_result:selected(A)},deps()).status==='primary','available primary remains primary');
ok(resolve({router_result:selected(A),failure:{kind:'account_unavailable'}},deps()).account_id===B.account_id,'unavailable primary falls back to next candidate');
ok(resolve({router_result:selected(A),failure:{kind:'provider_unavailable'}},deps()).provider_id!==A.provider_id,'provider failure excludes same provider');
ok(resolve({router_result:selected(A),failure:{kind:'quota_exhausted'}},deps()).account_id===B.account_id,'quota exhaustion falls back');
ok(resolve({router_result:selected(A),failure:{kind:'rate_limit'}},deps()).status==='no_fallback','rate limit requires explicit policy');
ok(resolve({router_result:selected(A),failure:{kind:'rate_limit'},policy:{allow_rate_limit_fallback:true}},deps()).status==='fallback','explicit rate-limit fallback works');
ok(activationAllows('rate_limit',null)===false,'rate limit disabled by default');
ok(resolve({router_result:selected(A),failure:{kind:'execution_failure'}},deps({candidates:[A]})).status==='no_fallback','no alternatives gives no_fallback');
ok(resolve({router_result:{status:'no_route'}},deps()).status==='no_fallback','no_route does not invent fallback');
ok(resolve(null).status==='no_fallback','null input controlled');
ok(resolve({router_result:selected(A),failure:{kind:'execution_failure'},visited:[B,C]},deps()).status==='no_fallback','visited candidates prevent loops');
ok(resolve({router_result:selected(A),failure:{kind:'execution_failure'},policy:{unauthorized:[B]}},deps()).account_id===C.account_id,'unauthorized candidate excluded');
ok(account.isAccountActive(A.account_id)===true,'live account remains active');
ok(quota.getCapacity(A.account_id)?.status==='unknown','live seed capacity remains unknown');
ok(model.providerOf(A.model_id)==='openrouter','model registry remains canonical');
ok(cap.supports(A.model_id,CAP)===true,'capability remains verified');
ok(typeof candidateKey(A)==='string','candidateKey remains canonical');
const src=require('fs').readFileSync(require.resolve('../fallback/lookup.js'),'utf8');ok(!/Math\.random|Date\.now|crypto\.random|fetch\(|axios/.test(src),'fallback lookup has no external/random execution');
ok(candidateSelectable(A,CAP,deps(),null)===true,'fixture candidate selectable');
console.log(`All ${n} assertions passed.`);
