'use strict';
const assert=require('node:assert/strict');
(async()=>{
  const engine=await import('../supabase/functions/aria-device-gateway/_shared/idea-to-mission.mjs');
  const p=await engine.buildIdeaMissionProposal('Quiero que ARIA cree un sistema para detectar errores y corregirlos con un nuevo agente antes de desplegar.');
  assert.equal(p.schema_version,'idea-to-mission-v1');
  assert.equal(p.queue_policy.auto_enqueue,false);
  assert.equal(p.queue_policy.auto_execute,false);
  assert.equal(p.summary.auto_enqueue,false);
  assert.equal(p.missions.length,4);
  assert.equal(p.missions[0].status,'proposed');
  assert.ok(p.missions[1].depends_on.includes('idea_mission_1'));
  assert.equal(engine.validateProposal(p).valid,true);
  const same=await engine.buildIdeaMissionProposal('  Quiero que ARIA cree un sistema para detectar errores y corregirlos con un nuevo agente antes de desplegar. ');
  assert.equal(same.fingerprint,p.fingerprint,'same idea must deduplicate');
  const human=await engine.buildIdeaMissionProposal('Quiero cambiar producción, pero necesito mi aprobación manual antes del merge.');
  assert.equal(human.classification.execution_state,'human_gate_or_governance_review');
  assert.equal(human.summary.human_gate_required,true);
  assert.equal(human.missions[2].human_gate.enabled,true);
  const blocked=await engine.buildIdeaMissionProposal('Necesito pagar una suscripción y usar una nueva API key para hacer esto.');
  assert.equal(blocked.classification.viability,'viable_now');
  assert.equal(blocked.classification.execution_state,'blocked_payment_or_credential');
  assert.equal(blocked.missions[2].status,'blocked');
  assert.ok(blocked.missions[2].blockers.some(x=>x.code==='PAYMENT_OR_CREDENTIAL'));
  const deferred=await engine.buildIdeaMissionProposal('Hazlo más adelante, cuando terminemos la fase actual.');
  assert.equal(deferred.classification.viability,'deferred');
  assert.ok(deferred.missions.slice(1).every(x=>x.status==='deferred'||x.status==='proposed'));
  const impossible=await engine.buildIdeaMissionProposal('Esto no es viable actualmente.');
  assert.equal(impossible.classification.viability,'not_viable_currently');
  assert.equal(impossible.missions[2].status,'blocked');
  const invalid={...p,queue_policy:{...p.queue_policy,auto_enqueue:true}};
  assert.equal(engine.validateProposal(invalid).valid,false);
  console.log('IDEA -> MISSION ENGINE: PASS');
})().catch(e=>{console.error(e);process.exit(1)});
