/** Mission 10.6 — Intelligent Router current contract tests */
const assert = require('assert');
const { route, collectCandidates, capacityAllows, version, registry } = require('../router/lookup.js');
const modelLookup = require('../models/lookup.js');
const modelReg = require('../models/registry.json');
const capLookup = require('../capabilities/lookup.js');
const capReg = require('../capabilities/registry.json');
const accountLookup = require('../accounts/lookup.js');
const accountReg = require('../accounts/registry.json');
const quotaLookup = require('../quota/lookup.js');
const quotaReg = require('../quota/registry.json');
const fs = require('fs');
const path = require('path');
let passed=0; const ok=(c,m)=>{assert.ok(c,m);passed++;console.log('PASS:',m)};
const CAP='text_generation', MODEL='google/gemini-2.5-flash-lite', PROVIDER='openrouter', ACCOUNT='acct_openrouter_primary';
console.log('=== Intelligent Router current contract ===');
ok(version==='aria-intelligent-router-v1.0.0','router version is current');
ok(modelLookup.providerOf(MODEL)===PROVIDER,'mediated model provider remains openrouter');
ok(modelLookup.getModel('google/gemini-3.5-flash-lite-direct')?.provider_id==='google','direct Gemini model is registered');
ok(modelLookup.getModel('google/gemini-3.5-flash-lite-direct')?.status==='available','direct Gemini model is available');
ok(capLookup.supports('google/gemini-3.5-flash-lite-direct',CAP)===true,'direct Gemini supports text_generation');
ok(accountLookup.version===accountReg.version,'Account Manager contract version matches registry');
ok(quotaLookup.version===quotaReg.version,'Quota Manager contract version matches registry');
ok(capLookup.version===capReg.version,'Capability Matrix contract version matches registry');
ok(modelLookup.version===modelReg.version,'Model Registry contract version matches registry');
ok(accountLookup.isAccountActive(ACCOUNT)===true,'seed account active');
ok(quotaLookup.getCapacity(ACCOUNT)?.status==='unknown','unknown capacity remains non-selectable');
ok(capacityAllows(ACCOUNT,MODEL)===false,'unknown capacity blocks selection');
ok(route({capability:CAP}).status==='no_route','current seed safely returns no_route');
ok(route({capability:'missing_capability'}).status==='no_route','missing capability returns no_route');
ok(route({capability:CAP,preferred_model:'fake-model'}).status==='no_route','fake model returns no_route');
ok(collectCandidates(CAP).length===0,'no candidates when capacity is unknown');
const src=fs.readFileSync(path.join(__dirname,'..','router','lookup.js'),'utf8');
ok(!/Math\.random|Date\.now|crypto\.random/.test(src),'router selection has no randomness/time');
ok(!/fetch\(|axios|http\.request|https\.request/.test(src),'router lookup has no network calls');
ok(!('models' in registry)&&!('accounts' in registry)&&!('capabilities' in registry)&&!('entries' in registry),'router registry has no copied foreign records');
console.log(`All ${passed} assertions passed.`);
