/** Mission 10.6 — Intelligent Router current contract tests */
const assert = require('assert');
const { route, collectCandidates, capacityAllows, version, registry } = require('../router/lookup.js');
const modelLookup = require('../models/lookup.js');
const modelReg = require('../models/registry.json');
const capLookup = require('../capabilities/lookup.js');
const capReg = require('../capabilities/registry.json');
const accountLookup = require('../accounts/lookup.js');
const accountReg = require('../accounts/registry.json');
const quotaLookup = require('../quota/lookup.js');
const quotaReg = require('../quota/registry.json');
const fs = require('fs');
const path = require('path');
let passed=0; const ok=(c,m)=>{assert.ok(c,m);passed++;console.log('PASS:',m)};
const CAP='text_generation';
const MODEL='google/gemini-3.5-flash-lite-direct';
const PROVIDER='google';
const ACCOUNT='acct_google_gemini_free';
const MEDIATED_MODEL='google/gemini-2.5-flash-lite';
console.log('=== Intelligent Router current contract ===');
ok(version==='aria-intelligent-router-v1.0.0','router version is current');
ok(modelLookup.providerOf(MEDIATED_MODEL)==='openrouter','mediated model provider remains openrouter');
ok(modelLookup.getModel(MODEL)?.provider_id==='google','direct Gemini model is registered');
ok(modelLookup.getModel(MODEL)?.status==='available','direct Gemini model is available');
ok(capLookup.supports(MODEL,CAP)===true,'direct Gemini supports text_generation');
ok(accountLookup.version===accountReg.version,'Account Manager contract version matches registry');
ok(quotaLookup.version===quotaReg.version,'Quota Manager contract version matches registry');
ok(capLookup.version===capReg.version,'Capability Matrix contract version matches registry');
ok(modelLookup.version===modelReg.version,'Model Registry contract version matches registry');
ok(accountLookup.isAccountActive(ACCOUNT)===true,'direct Gemini account active');
ok(quotaLookup.getCapacity(ACCOUNT)?.status==='available','direct Gemini capacity explicitly available');
ok(quotaLookup.getQuota(ACCOUNT)?.status==='available','direct Gemini quota explicitly available');
ok(quotaLookup.getQuota(ACCOUNT)?.rate_limit?.status==='unknown','unknown rate limit is preserved as unknown');
ok(capacityAllows(ACCOUNT,MODEL)===true,'available capacity remains selectable with unknown rate limit');
const selected=route({capability:CAP});
ok(selected.status==='selected','router selects an available text_generation route');
ok(selected.provider_id===PROVIDER,'router selects Google provider');
ok(selected.account_id===ACCOUNT,'router selects direct Gemini account');
ok(selected.model_id===MODEL,'router selects live direct Gemini model');
ok(route({capability:'missing_capability'}).status==='no_route','missing capability returns no_route');
ok(route({capability:CAP,preferred_model:'fake-model'}).status==='selected','invalid preference does not invent a route');
ok(route({capability:CAP,preferred_provider:'google'}).provider_id==='google','preferred provider selects Google when available');
ok(route({capability:CAP,preferred_account:ACCOUNT}).account_id===ACCOUNT,'preferred account selects direct Gemini');
ok(collectCandidates(CAP).some(c=>c.provider_id===PROVIDER&&c.account_id===ACCOUNT&&c.model_id===MODEL),'candidate enumeration includes live direct Gemini');
const src=fs.readFileSync(path.join(__dirname,'..','router','lookup.js'),'utf8');
ok(!/Math\.random|Date\.now|crypto\.random/.test(src),'router selection has no randomness/time');
ok(!/fetch\(|axios|http\.request|https\.request/.test(src),'router lookup has no network calls');
ok(!('models' in registry)&&!('accounts' in registry)&&!('capabilities' in registry)&&!('entries' in registry),'router registry has no copied foreign records');
console.log(`All ${passed} assertions passed.`);
