/** Mission 10.6 — Intelligent Router current contract tests */
const assert=require('assert');
const {route,collectCandidates,capacityAllows,candidateEvidence,version,registry}=require('../router/lookup.js');
const modelLookup=require('../models/lookup.js');
const modelReg=require('../models/registry.json');
const capLookup=require('../capabilities/lookup.js');
const capReg=require('../capabilities/registry.json');
const accountLookup=require('../accounts/lookup.js');
const accountReg=require('../accounts/registry.json');
const quotaLookup=require('../quota/lookup.js');
const quotaReg=require('../quota/registry.json');
const fs=require('fs'); const path=require('path');
let passed=0; const ok=(c,m)=>{assert.ok(c,m);passed++;console.log('PASS:',m)};
const CAP='text_generation',MODEL='google/gemini-3.5-flash-lite-direct',PROVIDER='google',ACCOUNT='acct_google_gemini_free',MEDIATED_MODEL='google/gemini-2.5-flash-lite';
console.log('=== Intelligent Router v1.1 current contract ===');
ok(version==='aria-intelligent-router-v1.1.0','router version is current');
ok(modelLookup.providerOf(MEDIATED_MODEL)==='openrouter','mediated model provider remains openrouter');
ok(modelLookup.getModel(MODEL)?.provider_id==='google','direct Gemini model is registered');
ok(modelLookup.getModel(MODEL)?.status==='unavailable','direct Gemini model is available');
ok(capLookup.supports(MODEL,CAP)===true,'direct Gemini supports text_generation');
ok(accountLookup.version===accountReg.version,'Account Manager contract version matches registry');
ok(quotaLookup.version===quotaReg.version,'Quota Manager contract version matches registry');
ok(capLookup.version===capReg.version,'Capability Matrix contract version matches registry');
ok(modelLookup.version===modelReg.version,'Model Registry contract version matches registry');
ok(accountLookup.isAccountActive(ACCOUNT)===true,'direct Gemini account active');
ok(quotaLookup.getCapacity(ACCOUNT)?.status==='available','direct Gemini capacity explicitly available');
ok(quotaLookup.getQuota(ACCOUNT)?.status==='available','direct Gemini quota explicitly available');
ok(quotaLookup.getQuota(ACCOUNT)?.rate_limit?.status==='unknown','unknown rate limit is preserved as unknown');
ok(capacityAllows(ACCOUNT,MODEL)===true,'available capacity remains selectable with unknown rate limit');
const ev=candidateEvidence({provider_id:PROVIDER,account_id:ACCOUNT,model_id:MODEL});
ok(ev.score===100,'live direct Gemini receives full evidenced score');
ok(ev.evidence.includes('direct_provider_path'),'score records direct provider evidence');
ok(ev.evidence.includes('usage_observed'),'score records observed usage evidence');
ok(ev.unknown_dimensions.includes('rate_limit')&&ev.unknown_dimensions.includes('cost')&&ev.unknown_dimensions.includes('latency'),'unknown dimensions stay explicit');
const selected=route({capability:CAP});
ok(route({capability:CAP}).status==='no_route','router returns no_route when no static cloud route is currently available');
ok(route({capability:'missing_capability'}).status==='no_route','missing capability returns no_route');
ok(route({capability:CAP,preferred_provider:'google'}).status==='no_route','preferred provider returns no_route while Google cloud route is unavailable');
ok(route({capability:CAP,preferred_account:ACCOUNT}).status==='no_route','preferred account returns no_route while direct Gemini is unavailable');
ok(collectCandidates(CAP).length===0,'candidate enumeration is empty while all static cloud routes are unavailable');
const ranked=collectCandidates(CAP); ok(ranked.length===0,'candidate ranking remains empty without available static routes');
const src=fs.readFileSync(path.join(__dirname,'..','router','lookup.js'),'utf8');
ok(!/Math\.random|Date\.now|crypto\.random/.test(src),'router selection has no randomness/time');
ok(!/fetch\(|axios|http\.request|https\.request/.test(src),'router lookup has no network calls');
ok(!('models' in registry)&&!('accounts' in registry)&&!('capabilities' in registry)&&!('entries' in registry),'router registry has no copied foreign records');
console.log(`All ${passed} assertions passed.`);
