const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'pwa/src/App.tsx'),'utf8');
const api=fs.readFileSync(path.join(root,'supabase/functions/aria-app-api-v3/index.ts'),'utf8');

assert.match(app,/api\('\/meditation\/overview'.*api\('\/capabilities'/s);
assert.match(app,/api\('\/diagnostics\/health'/);
assert.match(app,/successes\+\+/);
assert.match(app,/successes===3/);
assert.match(app,/No se pudieron actualizar todos los datos de Meditación IA/);
assert.match(app,/Reintentar ahora/);
assert.match(app,/lastSyncAt/);
assert.match(app,/meditation_overview: 15000/);
assert.match(app,/selectLiveMission/);
assert.match(app,/goal_source/);
assert.match(api,/async function enrichMission\(m:any, sb:any, includeEta=true\)/);
assert.match(api,/overview_fast/);
assert.match(api,/limit\(200\)/);
assert.match(api,/fastMissions/);
assert.match(api,/const latestUser=.*goal_source/s);
assert.match(api,/const hasLiveLease=.*lease_owner.*lease_until/s);
assert.match(api,/activeRank=.*running.*60.*waiting.*45/s);
assert.doesNotMatch(api,/activeRank=.*if\(s==="running"\)return 50/);
assert.match(api,/foreground_mission/);
assert.match(api,/const rawLive=/);
console.log('MEDITATION SYNC + FOREGROUND MISSION CONTRACT: PASS');

assert.ok(api.includes('path.endsWith("/cancel")'));
assert.match(api,/status: "cancelled"/);
console.log('MEDITATION MISSION CANCELLATION CONTRACT: PASS');

assert.match(app,/MeditationLiveExecution/);
assert.match(app,/EJECUCIÓN EN TIEMPO REAL/);
assert.match(app,/AHORA/);
assert.match(app,/Lo que ARIA acaba de hacer|Lo que ARIA acaba de hacer/);
assert.match(app,/executionHumanNow/);
assert.match(app,/executionHumanLog/);
assert.match(app,/executionOutcome/);
assert.match(app,/api\('\/missions\/'\s*\+\s*encodeURIComponent\(missionId\)\s*\+\s*'\/events\?live='/);
assert.match(app,/MEDITATION_LIVE_POLL_MS = 2500/);
assert.match(app,/useLiveSync\(load, session\.accessToken, MEDITATION_LIVE_POLL_MS\)/);
console.log('MEDITATION HUMAN LIVE EXECUTION CONTRACT: PASS');

assert.doesNotMatch(app,/Parte de Meditación IA se sincronizó;/);
assert.doesNotMatch(app,/SINCRONIZANDO…/);
assert.doesNotMatch(app,/0\.0%/);
assert.match(app,/Núcleo operativo activo/);
assert.match(app,/Transporte, modelos y cola disponibles/);
console.log('MEDITATION OLD RED/GENERIC UX REGRESSION CONTRACT: PASS');

const planner=fs.readFileSync(path.join(root,'supabase/functions/aria-planner-v11/index.ts'),'utf8');
assert.match(planner,/const live=await liveOperationalContext\(goal\)/);
assert.match(planner,/CONCLUSIÓN:/);
assert.match(planner,/QUÉ PASA:/);
assert.match(planner,/PROBLEMA:/);
assert.match(planner,/EVIDENCIA:/);
assert.match(planner,/SOLUCIÓN \/ SIGUIENTE PASO:/);
console.log('MEDITATION HUMAN ACTIONABLE RESULT CONTRACT: PASS');
