/** Mission 10.2 — Model Registry tests; direct Gemini is now LIVE-certified */
const assert=require('assert');
const {getModel,modelsByProvider,providerOf,listModelIds,version}=require('../models/lookup.js');
let passed=0;function ok(cond,msg){assert.ok(cond,msg);passed++;console.log('PASS:',msg);} console.log('=== Model Registry 10.2 tests ===');console.log('version:',version);
const m=getModel('google/gemini-2.5-flash-lite');ok(m!==null,'TEST 1: getModel returns the verified mediated model');ok(m.provider_id==='openrouter','TEST 1b: provider_id is openrouter');ok(m.upstream_provider_id==='google','TEST 1c: upstream_provider_id is google');ok(m.status==='available','TEST 1d: mediated status available');ok(!('api_key'in m)&&!('secret'in m)&&!('token'in(m.metadata||{})),'TEST 1e: no secrets');
const list=modelsByProvider('openrouter');ok(Array.isArray(list)&&list.length===1,'TEST 2: modelsByProvider(openrouter) returns 1 model');ok(list[0].model_id==='google/gemini-2.5-flash-lite','TEST 2b: correct model_id');
const direct=getModel('google/gemini-3.5-flash-lite-direct');ok(direct!==null,'TEST 3: direct Gemini current model is registered');ok(direct.provider_id==='google','TEST 3b: direct Gemini provider is google');ok(direct.status==='available','TEST 3c: direct Gemini is available after LIVE health');ok(providerOf('google/gemini-3.5-flash-lite-direct')==='google','TEST 3d: providerOf direct Gemini works');ok(modelsByProvider('google').length===2,'TEST 3e: Google registry includes current direct plus retired direct route');
ok(getModel('does-not-exist')===null,'TEST 4: nonexistent model returns null');ok(modelsByProvider('nonexistent-provider').length===0,'TEST 4b: unknown provider returns empty list');
const ids=listModelIds();ok(ids.length===new Set(ids).size,'TEST 5: no duplicate model_ids');ok(Array.isArray(m.capability_refs),'TEST 6: capability_refs array present');ok(Array.isArray(direct.capability_refs),'TEST 6b: direct model capability_refs array present');console.log('\nAll',passed,'assertions passed.');
