'use strict';
const assert = require('node:assert/strict');
const baseRouter = require('../router/lookup.js');
const omni = require('../router/omniroute.js');
const fs = require('node:fs');
const path = require('node:path');
const endpoint = 'http://127.0.0.1:20128/v1/chat/completions';
function evidence(overrides = {}) { return { status:'verified', healthy:true, capability:'omniroute.gateway', source:'aria.omniroute.capability', evidence_id:'phase7-cap-001', verified_at:'2026-10-05T00:00:00Z', endpoint, ...overrides }; }
const input = { opt_in:true, provider_id:'omniroute', account_id:'acct_omniroute_local', model_id:'ollama/qwen3:4b', capability:'text_generation', gateway_endpoint:endpoint, omniroute_provider:'ollama', availability_evidence:evidence() };
assert.equal(omni.VERSION,'aria-omniroute-router-integration-v1.0.0');
assert.equal(omni.isLoopbackEndpoint(endpoint),true);
assert.equal(omni.isLoopbackEndpoint('https://example.com/v1/chat/completions'),false);
assert.equal(omni.isLoopbackEndpoint('http://10.0.0.5:20128/v1/chat/completions'),false);
const selected=omni.selectOptIn(input);
assert.equal(selected.status,'selected');
assert.equal(selected.provider_id,'omniroute');
assert.equal(selected.model_id,'ollama/qwen3:4b');
assert.equal(selected.route_type,'omniroute_opt_in');
assert.equal(selected.gateway_endpoint,endpoint);
assert.equal(selected.omniroute_provider,'ollama');
assert.equal(selected.selection_evidence.evidence_id,'phase7-cap-001');
assert.equal(omni.selectOptIn({...input,opt_in:false}).reason,'opt_in_required');
assert.equal(omni.selectOptIn({...input,provider_id:'google'}).reason,'provider_not_omniroute');
assert.equal(omni.selectOptIn({...input,capability:'reasoning'}).reason,'capability_not_supported');
assert.equal(omni.selectOptIn({...input,gateway_endpoint:'https://evil.example/v1/chat/completions'}).reason,'loopback_endpoint_required');
assert.equal(omni.selectOptIn({...input,availability_evidence:evidence({healthy:false})}).reason,'availability_evidence_required');
assert.equal(omni.selectOptIn({...input,availability_evidence:evidence({status:'unverified'})}).reason,'availability_evidence_required');
assert.equal(omni.selectOptIn({...input,availability_evidence:evidence({capability:'other.capability'})}).reason,'availability_evidence_required');
assert.equal(omni.selectOptIn({...input,availability_evidence:evidence({endpoint:'http://127.0.0.1:20129/v1/chat/completions'})}).reason,'availability_evidence_required');
assert.equal(omni.selectOptIn({...input,model_id:''}).reason,'model_required');
assert.equal(omni.selectOptIn({...input,account_id:''}).reason,'account_required');
const staticRoute=baseRouter.route({capability:'text_generation'});
assert.equal(staticRoute.status,'no_route','default route remains unchanged and does not discover OmniRoute');
const source=fs.readFileSync(path.join(__dirname,'..','router','omniroute.js'),'utf8');
assert.doesNotMatch(source,/fetch\(|axios|http\.request|https\.request/);
assert.doesNotMatch(source,/process\.env|secret|api[_-]?key/i);
console.log('OMNIROUTE PHASE 7 ROUTER INTEGRATION: PASS');