const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'pwa/src/App.tsx'),'utf8');
const css=fs.readFileSync(path.join(root,'pwa/src/index.css'),'utf8');

assert.match(app,/AppPage = 'aria'.*'settings'/);
assert.match(app,/case '#settings'/);
assert.match(app,/function GlobalBottomNav/);
assert.match(app,/navigation.page === 'projects'/);
assert.match(app,/navigation.page === 'meditation'/);
assert.match(app,/navigation.page === 'capabilities'/);
assert.match(app,/navigation.page === 'settings'/);
assert.match(app,/page === 'settings'\s*\?/);
assert.match(app,/<GlobalBottomNav/);
assert.match(app,/Borrar caché y recargar/);
assert.match(app,/Actualizar app/);
assert.match(app,/Buscar actualización/);
assert.match(app,/caches.keys()/);
assert.match(app,/sessionSnapshot/);
assert.match(css,/.bottomNav{[^}]*overflow-x:auto/);
assert.match(css,/.bottomNav button{flex:0 0 66px/);
console.log('GLOBAL NAV + SETTINGS CONTRACT: PASS');

assert.doesNotMatch(app,/function Chat\([\s\S]{0,180}\bonSignOut/);
assert.doesNotMatch(app,/function Chat\([\s\S]{0,7000}<button className='ghost' onClick=\{onSignOut\}>Salir<\/button>/);
assert.doesNotMatch(app,/ARIA \/ CONTINUIDAD.*MEDITACIÓN IA.*Ejecución autónoma, verificación y Human Gates/);
assert.match(app,/function Meditation\(\{ session \}: \{ session: Session \}\)/);
assert.match(app,/<small>Medita<\/small>/);
assert.match(app,/<small>Cap\.<\/small>/);
assert.match(app,/<small>Config\.<\/small>/);
assert.match(css,/grid-template-columns:repeat\(7,minmax\(0,1fr\)\)/);
assert.match(css,/\.bottomNav button\{width:100%;min-width:0;/);
console.log('PWA UI CLEANUP CONTRACT: PASS');
