const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'pwa/src/App.tsx'),'utf8');
const project=fs.readFileSync(path.join(root,'pwa/src/ProjectWorkspace.tsx'),'utf8');
const css=fs.readFileSync(path.join(root,'pwa/src/index.css'),'utf8');
const api=fs.readFileSync(path.join(root,'supabase/functions/aria-app-api-v3/index.ts'),'utf8');
const runner=fs.readFileSync(path.join(root,'supabase/functions/aria-mission-runner-v22/index.ts'),'utf8');

for(const id of ['battlecruiser','cuevacoin','aria'])assert.match(project,new RegExp(id));
assert.match(app,/ProjectWorkspace/);
assert.match(app,/onProjects/);
assert.match(project,/CHAT EXCLUSIVO/);
assert.match(project,/same queue|misma cola/i);
assert.match(project,/visual_context/);
for(const tool of ['pen','marker','line','rect','circle','arrow','text','eraser'])assert.match(project,new RegExp("'"+tool+"'"));
assert.match(project,/toBlob/);
assert.match(project,/media\/upload-url/);
assert.match(project,/annotation_summary/);
assert.match(api,/PROJECTS/);
assert.match(api,/project_id/);
assert.match(api,/\/projects\//);
assert.match(api,/attachments/);
assert.match(runner,/function verifyStep/);
assert.match(runner,/explicitlyUnverified/);
assert.match(runner,/verification_failed/);
assert.match(runner,/__aria_verified_by_runner/);
assert.match(css,/visualBoardPanel/);
assert.match(project,/Cargar captura\/base/);
assert.match(project,/conversationId/);
assert.match(project,//projects\/.*conversation/);
assert.match(project,/Cargar captura\/base/);
assert.match(api,/aria_app_ensure_conversation/);
assert.match(api,/aria_app_save_message/);
assert.match(api,/looksLikeSimpleConversation/);
assert.match(api,/multimodal/);
assert.match(api,/createSignedUrl/);
const projectConstCount=(api.match(/const project = normalizeProjectContext\(body\);/g)||[]).length;
assert.equal(projectConstCount,2);
assert.match(css,/fileButton/);
assert.match(fs.readFileSync(path.join(root,'supabase/migrations/20260922171331_harden_meditation_notification_label_execute.sql'),'utf8'),/revoke execute/i);
console.log('PWA PROJECTS + ARTIA VISUAL + SHARED QUEUE + VERIFICATION CONTRACT: PASS');
