const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'pwa/src/App.tsx'),'utf8');
const project=fs.readFileSync(path.join(root,'pwa/src/ProjectWorkspace.tsx'),'utf8');
const css=fs.readFileSync(path.join(root,'pwa/src/index.css'),'utf8');
const api=fs.readFileSync(path.join(root,'supabase/functions/aria-app-api-v3/index.ts'),'utf8');
const runner=fs.readFileSync(path.join(root,'supabase/functions/aria-mission-runner-v22/index.ts'),'utf8');

for(const id of ['battlecruiser','cuevacoin','aria'])assert.match(project,new RegExp(id));
assert.match(app,/ProjectWorkspace/);
assert.match(app,/onProjects/);
assert.match(project,/CHAT EXCLUSIVO/);
assert.match(project,/same queue|misma cola|una sola cola/i);
assert.match(project,/visual_context/);
for(const tool of ['pen','marker','line','rect','circle','arrow','text','eraser'])assert.match(project,new RegExp("'"+tool+"'"));
assert.match(project,/toBlob/);
assert.match(project,/media\/upload-url/);
assert.match(project,/annotation_summary/);
assert.match(api,/PROJECTS/);
assert.match(api,/project_id/);
assert.match(api,/\/projects\//);
assert.match(api,/attachments/);
assert.match(runner,/function verifyStep/);
assert.match(runner,/explicitlyUnverified/);
assert.match(runner,/verification_failed/);
assert.match(runner,/__aria_verified_by_runner/);
assert.match(css,/visualBoardPanel/);
assert.match(project,/Cargar imagen|Cargar captura de referencia/);
assert.match(project,/conversationId/);
assert.match(project,/\/projects\/.*conversation/);
assert.match(api,/aria_app_ensure_conversation/);
assert.match(api,/aria_app_save_message/);
assert.match(api,/looksLikeSimpleConversation/);
assert.match(api,/multimodal/);
assert.match(api,/createSignedUrl/);
const projectConstCount=(api.match(/const project = normalizeProjectContext\(body\);/g)||[]).length;
assert.equal(projectConstCount,2);
assert.match(app,/bottomNav/);
assert.match(app,/onPointerDown=\{onSwipeStart\}/);
assert.match(app,/screenIndicator/);
assert.match(app,/conversationId/);
assert.match(app,/pageBodyViewport/);
assert.match(app,/e\.key === 'Enter'/);
assert.match(project,/Lápiz/);
assert.match(project,/PROJECT PREVIEW/);
assert.match(project,/invalid_or_expired_session/);
assert.match(project,/La sesión de ARIA expiró/);
assert.match(project,/previewPaused/);
assert.match(project,/Pausa la vista previa antes de pintar/);
assert.match(project,/project_preview:true/);
assert.match(project,/Crear misión con este diseño/);
assert.match(project,/await onMission/);
assert.match(project,/composerStatus/);
assert.match(project,/projectChatRef/);
assert.match(project,/Marcador/);
assert.match(project,/Borrador/);
assert.doesNotMatch(project,/window\.prompt/);
assert.doesNotMatch(css,/min-width:560px/);
assert.match(css,/height:100dvh/);
assert.match(css,/body\{overflow:hidden/);
assert.match(css,/\.bottomNav/);
assert.match(css,/\.pageBodyViewport/);
assert.match(css,/\.canvasWrap\{overflow:auto/);
assert.match(css,/fileButton/);
assert.match(css,/\.screenIndicator/);
assert.match(css,/\.visualPreviewControls/);
assert.match(fs.readFileSync(path.join(root,'supabase/migrations/20260922171331_harden_meditation_notification_label_execute.sql'),'utf8'),/revoke execute/i);
console.log('PWA PROJECTS + ARTIA VISUAL + SHARED QUEUE + VERIFICATION CONTRACT: PASS');
