'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const source=fs.readFileSync('.github/workflows/supabase-canonical-deploy.yml','utf8');
const workerPwa=fs.readFileSync('worker.js','utf8');
for(const fn of ['aria-planner-v10','aria-autonomy-supervisor-v10','aria-mission-runner-v17','aria-canonical-runtime-v1','aria-direct-v1','aria-memory-v2','aria-device-gateway']) assert.match(source,new RegExp(`functions deploy ${fn}\\b`),`${fn} must be deployed`);
assert.doesNotMatch(source,/functions deploy aria-mission-runner-v14\b/);
assert.doesNotMatch(source,/functions deploy aria-mcp-server-grok-v2\b/);
assert.doesNotMatch(source,/functions deploy aria-mcp-oauth-grok-v2\b/);
assert.match(source,/supabase link --project-ref "\$SUPABASE_PROJECT_REF"/,'canonical deploy must link the target project before migration push');
assert.match(source,/supabase migration fetch --linked --yes/,'canonical deploy must fetch remote migration files before push');
assert.match(source,/supabase db push --include-all/,'canonical deploy must apply pending migrations');
assert.match(workerPwa,/const isShell=shellPath===\\"\\/\\"\\|\\|shellPath===\\"\\/index\\.html\\"\\|\\|shellPath===\\"\\/sw\\.js\\"\\|\\|shellPath===\\"\\/manifest\\.json\\"/,'PWA shell paths must be explicitly identified for cache control');
assert.match(workerPwa,/responseHeaders\.set\\(\\"cache-control\\",\\"no-store, max-age=0\\"\\)/,'PWA shell must disable browser/CDN cache');
assert.match(source,/remote_hashes/,'canonical deploy must compare migration content against remote history');
assert.match(source,/MIGRATION_PENDING=/,'canonical deploy must report pending migrations');
assert.match(source,/MIGRATION_ALREADY_APPLIED=/,'canonical deploy must skip already-applied migrations');
assert.match(source,/LEGACY_MIGRATION_IGNORED=/,'canonical deploy must quarantine legacy malformed migration filenames');
assert.match(source,/duplicate pending migration versions/,'canonical deploy must fail on duplicate pending versions');
console.log('SUPABASE CANONICAL DEPLOY CONTRACT: PASS');
