'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {createWorldModelV2}=require('../memory/world-model-v2');
const src=fs.readFileSync('memory/world-model-v2.js','utf8');
const contract=fs.readFileSync('memory/world-model-contract-v2.md','utf8');
assert.equal(/api[_-]?key\s*[:=]\s*["'][A-Za-z0-9_\-]{12,}["']/.test(src),false);
assert.equal(/BEGIN (RSA|OPENSSH|PRIVATE) KEY/.test(src),false);
assert.equal(/process\.env/.test(src),false);
assert.equal(/globalThis\.fetch|fetch\s*\(/.test(src),false);
assert.ok(contract.includes('does not authorize execution'));
assert.ok(contract.includes('Unknown state remains `unknown`'));
const safe=createWorldModelV2({entities:[{id:'secret-ref',type:'secret_ref',metadata:{ref:'ref:credential-1'},provenance:{source:'registry',confidence:.9}}]});
assert.equal(safe.integrity().valid,true);
const unsafe=createWorldModelV2({entities:[{id:'secret-material',type:'secret_ref',metadata:{api_key:'not-a-real-key'},provenance:{source:'bad-source',confidence:.9}}]});
assert.equal(unsafe.integrity().valid,false);
assert.equal(unsafe.integrity().secret_material_exposed,true);
assert.equal(JSON.stringify(safe.snapshot()).includes('credential-1'),true);
assert.equal(JSON.stringify(safe.snapshot()).includes('not-a-real-key'),false);
console.log('WORLD MODEL V2 SECURITY: PASS — no embedded secret material, environment/network authority, and unsafe secret metadata fails closed');
