import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,SECRET=Deno.env.get("ARIA_RUNTIME_SHARED_SECRET")!;
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const eq=(a:string,b:string)=>a.length===b.length&&[...a].reduce((n,_,i)=>n|(a.charCodeAt(i)^b.charCodeAt(i)),0)===0;
async function auth(r:Request){const h=r.headers.get("authorization")||"",t=h.startsWith("Bearer ")?h.slice(7):"",c=r.headers.get("x-aria-autonomy-token")||"";if(SECRET&&t&&eq(t,SECRET))return true;const {data,error}=await sb.rpc("aria_autonomy_cron_authorize",{p_token:c});return !error&&data===true}
async function recover(){const {data,error}=await sb.rpc("aria_autonomy_recover_stale_missions",{p_stale_after:"00:02:00"});if(error)throw new Error(error.message);return Number(data||0)}
async function learn(){const cut=new Date(Date.now()-60*60*1000).toISOString();const {data,error}=await sb.schema("aria_internal").from("mission_state").select("mission_id,goal,status,metadata,last_stderr,last_stdout").in("status",["succeeded","blocked","failed","timeout","cancelled"]).gt("updated_at",cut);if(error)throw new Error(error.message);let created=0;for(const m of data||[]){const {data:e}=await sb.schema("aria_internal").from("autonomy_learnings").select("lesson_id").eq("mission_id",m.mission_id).limit(1);if(e?.length)continue;const {error:ie}=await sb.schema("aria_internal").from("autonomy_learnings").insert({mission_id:m.mission_id,goal_id:m.metadata?.goal_id??null,category:m.status==="succeeded"?"verified_success":"operational_failure",summary:`Observed ${m.status}: ${(m.goal||"").slice(0,220)}`,evidence:{status:m.status,stderr:m.last_stderr||null,stdout_sample:(m.last_stdout||"").slice(0,800)},confidence:m.status==="succeeded"?0.9:0.75,reusable:true});if(!ie)created++}return {scanned:data?.length||0,created}}
async function nextGoal(){const {data,error}=await sb.schema("aria_internal").from("autonomy_goals").select("*").eq("status","queued").lte("next_run_at",new Date().toISOString()).order("priority",{ascending:true}).limit(1);if(error)throw new Error(error.message);return data?.[0]||null}
async function makeMission(g:any){const id=`mission_${crypto.randomUUID()}`,sd=g.goal_id==="autonomy-selfdevelopment-audit";const {data,error}=await sb.rpc("aria_mission_create",{p_mission:{mission_id:id,status:"queued",goal:g.goal,current_step:0,completed_steps:0,checkpoint:{},metadata:{source:"autonomy_supervisor_v10",goal_id:g.goal_id,policy:"safe-progress-v5",self_development:sd,self_development_mode:sd?"audit_only":null,human_gate_required:["HIGH_RISK_WRITE","destructive","production_merge"]}}});if(error)throw new Error(error.message);await sb.schema("aria_internal").from("autonomy_goals").update({status:"running",attempts:(g.attempts||0)+1,last_mission_id:id,updated_at:new Date().toISOString()}).eq("goal_id",g.goal_id);return data}
Deno.serve(async r=>{if(r.method!=="POST")return out({error:"method_not_allowed"},405);if(!(await auth(r)))return out({error:"unauthorized"},401);try{const recovered=await recover(),learning=await learn();const {count,error}=await sb.schema("aria_internal").from("mission_state").select("mission_id",{count:"exact",head:true}).in("status",["planning","running"]);if(error)throw new Error(error.message);const active=count||0;let goal=null,mission=null;if(active===0){goal=await nextGoal();if(goal)mission=await makeMission(goal)}return out({ok:true,recovered,learning,active_before:active,goal_id:goal?.goal_id??null,mission_created:mission?.mission_id??null})}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},200)}});