'use strict';

const crypto = require('crypto');

function createSelfDevelopmentSandbox({ workspace, snapshotStore = null, protectedPaths = [], baseBranch = 'main' } = {}) {
  if (!workspace || typeof workspace.read !== 'function' || typeof workspace.apply !== 'function' || typeof workspace.createBranch !== 'function') throw new TypeError('branch_workspace_boundary_required');
  if (typeof workspace.openPullRequest !== 'function') throw new TypeError('pull_request_boundary_required');
  const protectedSet = new Set((Array.isArray(protectedPaths) ? protectedPaths : []).map(String));
  const sessions = new Map();

  function sessionId(seed = '') {
    return `sandbox_${crypto.createHash('sha256').update(String(seed)).digest('hex').slice(0, 20)}`;
  }

  function branchName(id) { return `aria/self-development/${id.slice(-20)}`; }
  function assertMutable(path) {
    if (!path || protectedSet.has(String(path))) throw new Error('protected_path');
  }

  async function create({ objective, seed = '' } = {}) {
    const id = sessionId(`${objective || ''}:${seed}:${sessions.size}`);
    const branch = branchName(id);
    await workspace.createBranch(branch, baseBranch);
    const state = { id, branch, objective: objective || 'self_development', base_branch: baseBranch, status: 'open', changes: [], created_at: new Date().toISOString() };
    sessions.set(id, state);
    return Object.freeze({ ...state });
  }

  async function stage(id, change) {
    const state = sessions.get(id);
    if (!state || state.status !== 'open') throw new Error('sandbox_session_closed');
    if (!change || typeof change.path !== 'string') throw new TypeError('change_required');
    assertMutable(change.path);
    const before = await workspace.read(change.path, state.branch);
    const entry = { type: change.type, path: change.path, content: change.content, before, staged_at: new Date().toISOString() };
    state.changes.push(entry);
    return Object.freeze({ status: 'staged', session_id: id, branch: state.branch, path: change.path, before });
  }

  async function run(id, { apply = false } = {}) {
    const state = sessions.get(id);
    if (!state || state.status !== 'open') throw new Error('sandbox_session_closed');
    const results = [];
    for (const change of state.changes) {
      if (!apply) results.push({ path: change.path, status: 'simulated', type: change.type, branch: state.branch });
      else {
        assertMutable(change.path);
        const result = await workspace.apply({ ...change, branch: state.branch, risk_level: change.risk_level || 'low' });
        results.push({ path: change.path, result });
      }
    }
    return Object.freeze({ status: 'succeeded', session_id: id, branch: state.branch, mode: apply ? 'sandbox_apply' : 'dry_run', results });
  }

  async function promote(id, { verifier = null, tests = null, title = null, body = null } = {}) {
    const state = sessions.get(id);
    if (!state || state.status !== 'open') throw new Error('sandbox_session_closed');
    if (typeof verifier !== 'function') return { status: 'blocked', reason: 'promotion_verifier_required' };
    const evidence = await verifier({ session: { ...state, changes: [...state.changes] }, tests });
    if (!evidence || evidence.passed !== true) return { status: 'blocked', reason: 'verification_required', evidence: evidence || null };
    const pullRequest = await workspace.openPullRequest({
      branch: state.branch,
      title: title || `chore: ARIA self-development ${state.id}`,
      body: body || 'Generated by ARIA after sandbox validation; merge remains governed by repository protections.'
    });
    state.status = 'promotion_pending';
    state.pull_request = pullRequest?.number || pullRequest?.url || null;
    return Object.freeze({ status: 'promotion_pending', session_id: id, branch: state.branch, evidence, pull_request: state.pull_request });
  }

  async function discard(id) {
    const state = sessions.get(id);
    if (!state) return { status: 'not_found' };
    state.status = 'discarded';
    return Object.freeze({ status: 'discarded', session_id: id, branch: state.branch });
  }

  return Object.freeze({ create, stage, run, promote, discard });
}

module.exports = Object.freeze({ createSelfDevelopmentSandbox });
