// RWHT Android runtime contract: governed conversation probe + safe read-only fallback.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!, KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, SECRET=Deno.env.get("ARIA_RUNTIME_SHARED_SECRET")!;
const EAS_PROJECT_ID="1b23b091-f7b6-4dc2-b328-c8e5ec07de57"; const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false,autoRefreshSession:false}}).schema("aria_internal");
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const eq=(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0};
async function auth(r:Request){const h=r.headers.get("authorization")||"";const t=h.startsWith("Bearer ")?h.slice(7):"";if(SECRET&&t&&eq(t,SECRET))return true;const c=r.headers.get("x-aria-autonomy-token");if(!c)return false;const {data,error}=await db.rpc("aria_autonomy_cron_authorize",{p_token:c});return !error&&data===true}
const modelStep=(id:string,route:any,prompt:string)=>({id,operation:"text_generation",executor_type:"model",target:{type:"model",provider_id:route.provider_id,account_id:route.account_id,model_id:route.model_id},capability:"text_generation",input:{payload:{prompt,max_tokens:1800,temperature:0}},risk:"READ",timeout_ms:90000,policy:{},verify:{response_content_contains:"FINDINGS"},selection:{review_role:"forensic_reviewer",capability_status:route.capability_status||"unknown",evidence_type:route.evidence_type||"unknown",evidence_ref:route.evidence_ref||null}});
const agentStep=(id:string,a:any,prompt:string)=>({id,operation:"delegate",executor_type:"agent",target:{type:"agent",agent_id:a.agent_id},capability:"delegation",input:{goal:`ARIA forensic audit (${a.role||"agent"})`,prompt,max_tokens:1800},risk:"READ",timeout_ms:120000,policy:{asset_forensic:true},verify:{},selection:{review_role:a.role,model_id:a.model_id||null}});
const repairStep=(goal:string,context:any)=>[{id:"repair_1",operation:"delegate",executor_type:"agent",target:{type:"agent",agent_id:"aria-agent-coding-v1"},capability:"coding",input:{goal:"Repair verified ARIA failure",prompt:`REPAIR REQUIRED. Resolve the underlying cause, not the symptom. Work on a non-main governed branch, make the smallest justified change, test it, and return structured EVIDENCE with exact artifacts and any Human Gate. Do not claim success from prose alone. Goal: ${goal}. Context: ${JSON.stringify(context).slice(0,7000)}`,max_tokens:2600},risk:"LOW_RISK_WRITE",timeout_ms:180000,policy:{repair_required:true,mutating_operation_required:true,non_main_branch_required:true,test_evidence_required:true,do_not_claim_text_only_success:true,production_merge_requires_human_gate:true},verify:{},selection:{review_role:"coder",write_route:"github_app_governed_or_agent_runtime"}}];
const changeStep=(goal:string,context:any)=>[{id:"change_1",operation:"delegate",executor_type:"agent",target:{type:"agent",agent_id:"aria-agent-coding-v1"},capability:"coding",input:{goal:"Execute governed implementation change",prompt:`This is a real implementation/build/create/change task. Inspect current implementation, make the smallest concrete mutation on a non-main governed branch, add/update focused tests or CI evidence, and return structured EVIDENCE. Production merge/deploy is a Human Gate. Goal: ${goal}. Context: ${JSON.stringify(context).slice(0,7000)}`,max_tokens:2800},risk:"LOW_RISK_WRITE",timeout_ms:180000,policy:{mutating_operation_required:true,non_main_branch_required:true,test_evidence_required:true,do_not_claim_text_only_success:true,production_merge_requires_human_gate:true},verify:{},selection:{review_role:"coder",write_route:"github_app_governed_or_agent_runtime"}}];
async function modelRoutes(){const [{data:m},{data:c},{data:a}]=await Promise.all([db.from("model_registry").select("model_id,provider_id,status,enabled"),db.from("capability_matrix").select("model_id,status,evidence_type,evidence_ref").eq("capability_id","text_generation"),db.from("account_registry").select("account_id,provider_id,status,enabled")]);return (m||[]).filter((x:any)=>x.enabled&&x.status==="available").map((x:any)=>{const cap=(c||[]).find((z:any)=>z.model_id===x.model_id);const acc=(a||[]).find((z:any)=>z.provider_id===x.provider_id&&z.enabled&&["available","active"].includes(String(z.status)));return acc?{model_id:x.model_id,provider_id:x.provider_id,account_id:acc.account_id,capability_status:cap?.status||"unknown",evidence_type:cap?.evidence_type||"unknown",evidence_ref:cap?.evidence_ref||null,score:(cap?.status==="verified"?100:50)+(x.provider_id==="google"?10:0)}:null}).filter(Boolean).sort((x:any,y:any)=>y.score-x.score)}
async function assetPlan(goal:string){const g=goal.toLowerCase(); if(/(?:modelo individual:|model individual:)/i.test(goal)){const target=(goal.match(/(?:modelo individual:|model individual:)\s*([^\s]+)/i)||[])[1]||"";const routes=await modelRoutes();const route=routes.find((r:any)=>r.model_id===target);if(!route)return out({error:"target_model_unavailable",target},409);return out({ok:true,plan:{goal,steps:[modelStep("asset_1",route,`FINDINGS. Audit only the exact target model ${target}. Use the live route selected by ARIA. Discuss availability, route, account, capability evidence, observed behavior, limits, fallback and risks. Do not invent. Finish with VERDICT.`)],planner_version:"aria-planner-v11-asset-forensic-v1",asset_forensic:true,target_type:"model",target}})}
if(/(?:agente individual:|agent individual:)/i.test(goal)){const target=(goal.match(/(?:agente individual:|agent individual:)\s*([^\s]+)/i)||[])[1]||"";const {data:a}=await db.from("agent_catalog").select("agent_id,role,model_id,status,capabilities,max_risk").eq("agent_id",target).maybeSingle();if(!a||a.status!=="available")return out({error:"target_agent_unavailable",target},409);return out({ok:true,plan:{goal,steps:[agentStep("asset_1",a,`FINDINGS. Audit the exact target agent ${target}. Compare its live behavior with its registered role, capabilities, model, risk and limits. Use only evidence available to you; do not invent. Finish with VERDICT.`)],planner_version:"aria-planner-v11-asset-forensic-v1",asset_forensic:true,target_type:"agent",target}})}
if(/(?:dispositivo\/executor individual:|device\/executor individual:)/i.test(goal)){const target=(goal.match(/(?:dispositivo\/executor individual:|device\/executor individual:)\s*([^\s]+)/i)||[])[1]||"";return out({ok:true,plan:{goal,steps:[{id:"asset_1",operation:"shell.execute",executor_type:"device",target:{type:"device",device_id:target},input:{command:"echo ARIA_ASSET_FORENSIC_DEVICE_OK"},risk:"READ",timeout_ms:30000,policy:{asset_forensic:true,safe_read_only:true},verify:{expected_exit_code:0,stdout_contains:"ARIA_ASSET_FORENSIC_DEVICE_OK"}}],planner_version:"aria-planner-v11-asset-forensic-v1",asset_forensic:true,target_type:"device",target}})}
if(/(?:proveedor ia individual:|individual ai provider:)/i.test(goal)){const target=(goal.match(/(?:proveedor IA individual:|individual AI provider:)\s*([^ /]+)/i)||[])[1]||"";const routes=(await modelRoutes()).filter((r:any)=>r.provider_id===target);if(!routes.length)return out({error:"target_provider_unavailable",target},409);return out({ok:true,plan:{goal,steps:[modelStep("asset_1",routes[0],`FINDINGS. Audit the exact provider ${target} through the real route selected by ARIA. Check connectivity, authentication state as observable, capability behavior, errors, latency signals, security boundaries and fallbacks. Do not expose credentials or invent. Finish with VERDICT.`)],planner_version:"aria-planner-v11-asset-forensic-v1",asset_forensic:true,target_type:"provider",target}})}
return null}
function easPlan(g:string,context:any){const s=g.toLowerCase();let op:string|null=null;for(const x of ["connection_status","workflow_definitions","workflow_list","workflow_info","build_list","build_info","build_logs","workflow_dispatch"])if(s.includes(`eas.${x}`))op=`eas.${x}`;if(!op)return null;const input:any={};if(op.endsWith("workflow_list")||op.endsWith("build_list"))input.limit=20;if(op.endsWith("workflow_info"))input.runId=context?.runId;if(op.endsWith("build_info")||op.endsWith("build_logs"))input.buildId=context?.buildId;if(op.endsWith("workflow_dispatch")){input.gitRef=context?.gitRef;input.fileName=context?.fileName;input.inputs=context?.inputs}return out({ok:true,plan:{goal:g,steps:[{id:"eas_1",operation:op,executor_type:"eas",target:{type:"eas",project_id:EAS_PROJECT_ID},input,risk:"READ",timeout_ms:120000,policy:{},verify:{} }],planner_version:"aria-planner-v11-eas-aware",cognitive_context:context}})}
async function operationAuditPlan(goal:string,context:any){
const match=goal.match(/(?:auditar operación ejecutora individual:|audit executor operation:|audit operation:)\s*([a-z0-9_.-]+)/i);if(!match)return null;const target=match[1];const {data:agents}=await db.from("agent_catalog").select("agent_id,role,model_id,status,max_risk,capabilities,scope").eq("status","available").order("agent_id");const preferred=["aria-agent-research-v1","aria-agent-reviewer-v1","aria-agent-security-v1"];const agent=(agents||[]).find((a:any)=>preferred.includes(a.agent_id))||(agents||[])[0];if(agent){const prompt=`FINDINGS. Audit ONLY the exact executor operation ${target}. Inspect the real ARIA repository and registered runtime evidence with read-only governed tools. Cover contract, availability, permissions/governance, failure modes, retries, verification, observability, security, and whether the runtime actually consumes this operation. Separate CONFIRMED from HYPOTHESIS. Do not mutate anything. Finish with VERDICT. Original goal: ${goal}. Context: ${JSON.stringify(context).slice(0,5000)}`;return out({ok:true,plan:{goal,steps:[{id:"operation_audit_1",operation:"delegate",executor_type:"agent",target:{type:"agent",agent_id:agent.agent_id},capability:"delegation",input:{goal:"Forensic operation audit",prompt,max_tokens:2200},risk:"READ",timeout_ms:120000,policy:{asset_forensic:true,tool_use:true,safe_read_only:true,target_operation:target},verify:{response_content_contains:"FINDINGS"},selection:{review_role:agent.role,model_id:agent.model_id||null}}],planner_version:"aria-planner-v11-operation-forensic-v1",asset_forensic:true,target_type:"operation",target}});}return null;}
function selfAuditPlan(goal:string,context:any,routes:any,agents:any[]){const scope=`FINDINGS. Independent forensic review of ARIA. Scope: ${goal}. Context: ${JSON.stringify(context).slice(0,7000)}. Confirm facts from execution evidence; separate hypotheses; cover architecture, runtime, DB, memory, learning, planning, execution, models, agents, devices, tools, security, recovery.`;const steps:any[]=[];routes.slice(0,4).forEach((r:any,i:number)=>steps.push(modelStep(`review_model_${i+1}`,r,`${scope} Use model ${r.model_id}. Begin with FINDINGS and finish with VERDICT.`)));agents.slice(0,4).forEach((a:any,i:number)=>steps.push(agentStep(`review_agent_${i+1}`,a,`${scope} Independent specialist pass as ${a.role}. Begin with FINDINGS and finish with VERDICT.`)));return {goal,steps,planner_version:"aria-planner-v11-forensic-multi-route-v1",self_audit:true}}
Deno.serve(async r=>{if(r.method!=="POST")return out({error:"method_not_allowed"},405);if(!(await auth(r)))return out({error:"unauthorized"},401);const b=await r.json().catch(()=>({}));const goal=typeof b.goal==="string"?b.goal.trim():"";const context=b.context&&typeof b.context==="object"&&!Array.isArray(b.context)?b.context:{};if(!goal)return out({error:"goal_required"},400);try{const asset=await assetPlan(goal);if(asset)return asset;const eas=easPlan(goal,context);if(eas)return eas;const g=goal.toLowerCase();
const runtimeProbe=/(?:^|\b)(hola|test|prueba|esto\s+(?:esta|está)\s+funcionando|funcionando\??)(?:\b|$)/i.test(g);
if(runtimeProbe){
  const routes=await modelRoutes();
  const r=routes.find((x:any)=>x.provider_id==="openrouter") || routes[0];
  if(!r)return out({error:"no_available_text_model"},503);
  const probeStep={id:"probe_model_1",operation:"text_generation",executor_type:"model",target:{type:"model",provider_id:r.provider_id,account_id:r.account_id,model_id:r.model_id},capability:"text_generation",input:{payload:{prompt:"FINDINGS. ARIA runtime probe. Goal: "+goal+". Return the exact marker ARIA_RUNTIME_PROBE_OK and one short factual sentence about the model response. Do not claim external actions.",max_tokens:120,temperature:0}},risk:"READ",timeout_ms:60000,policy:{runtime_probe:true},verify:{response_content_contains:"ARIA_RUNTIME_PROBE_OK"},selection:{runtime_probe:true,model_id:r.model_id,provider_id:r.provider_id,account_id:r.account_id}};
  return out({ok:true,plan:{goal,steps:[{id:"probe_health_1",operation:"health",executor_type:"connector",target:{type:"connector",connector_id:"supabase"},input:{},risk:"READ",timeout_ms:15000,policy:{runtime_probe:true},verify:{}},probeStep],planner_version:"aria-planner-v11-runtime-probe-v1",runtime_probe:true}});
}
if(/^diagnose and resolve the verified failure from mission\b/i.test(goal))return out({ok:true,plan:{goal,steps:repairStep(goal,context),planner_version:"aria-planner-v11-dynamic-repair-aware-v4",dynamic_failure_repair:true}});const repairIntent=/\b(repair|repairs|fix|fixes|resolve|resolver|reparar|repara|corregir|corrige|restaurar|restaura)\b/.test(g);if(repairIntent)return out({ok:true,plan:{goal,steps:repairStep(goal,context),planner_version:"aria-planner-v11-governed-repair-v1",repair_intent:true,mutating_operation_required:true}});const operationAudit=await operationAuditPlan(goal,context);if(operationAudit)return operationAudit;if(/self[- ]audit|forensic self|super forensic|deep forensic|auditar resiliencia|security hardening|performance hardening|auditoría profunda|cross-model independent review/i.test(g)){const routes=await modelRoutes();const {data:agents}=await db.from("agent_catalog").select("agent_id,role,model_id,status,max_risk").eq("status","available").order("agent_id");return out({ok:true,plan:selfAuditPlan(goal,context,routes,agents||[])})}const mutationIntent=/\b(change|changes|build|builds|create|creates|implement|implementation|implementing|repair|repairs|fix|fixes|modify|modifies|update|updates|add|adds|remove|removes|develop|development|refactor|refactoring|write|writes|migrate|migration|promote|promotion|corregir|corrige|corregir|crear|cree|crear|implementar|implemente|modificar|modifica|actualizar|actualiza|añadir|anadir|eliminar|elimina|desarrollar|desarrolle|refactorizar|refactoriza|escribir|escriba|migrar|migra|promover|promueva)\b/.test(g);const readOnly=/\b(audit|review|investigate|measure|verify|inspect|diagnose|forensic|assessment|assess|analy[sz]e|benchmark)\b/.test(g);if(mutationIntent&&!readOnly)return out({ok:true,plan:{goal,steps:changeStep(goal,context),planner_version:"aria-planner-v11-governed-change-v2",change_intent:true,mutating_operation_required:true}});if(goal.startsWith("IA conversacional:")){const routes=await modelRoutes();const r=routes.find((x:any)=>x.provider_id==="openrouter") || routes[0];return out({ok:true,plan:{goal,steps:[modelStep("model_1",r,`Conversation task: ${goal.replace(/^IA conversacional:\s*/i,"")}\nDo not claim actions were executed.`)],planner_version:"aria-planner-v11-conversation-aware"}})}if(/gemini|modelo|openrouter/.test(g)){const routes=await modelRoutes();const r=routes[0];if(!r)return out({error:"no_available_text_model"},503);return out({ok:true,plan:{goal,steps:[modelStep("model_1",r,`ARIA verification task. Goal: ${goal}. Reply briefly with evidence and no secrets.`)],planner_version:"aria-planner-v11-model-aware"}})}const routes=await modelRoutes();
const r=routes[0];
if(!r)return out({error:"no_available_text_model"},503);
return out({ok:true,plan:{goal,steps:[modelStep("general_read_1",r,`FINDINGS. Perform a read-only governed analysis of this ARIA goal: ${goal}. Use only the context supplied by the runtime. Do not claim external actions were executed, do not invent evidence, and finish with VERDICT.`)],planner_version:"aria-planner-v11-safe-readonly-fallback-v2",safe_readonly_fallback:true}})}catch(e){return out({error:"planner_internal_error",detail:e instanceof Error?e.message:String(e)},500)}});