/**
 * ARIA Fallback Engine lookup helpers (Mission 10.7) — pure, deterministic,
 * secret-free. Accepts credential references from the governed credential
 * boundary; never accepts raw secrets.
 */
const router = require('../router/lookup.js');
const modelLookup = require('../models/lookup.js');
const capLookup = require('../capabilities/lookup.js');
const accountLookup = require('../accounts/lookup.js');
const registry = require('./registry.json');
const PRIMARY='primary', FALLBACK='fallback', NO_FALLBACK='no_fallback';
const POLICY_NOTE='POLICY INPUT NOT IMPLEMENTED';
const ACTIVATIONS={provider_unavailable:{exclude:'provider'},account_unavailable:{exclude:'account'},credential_failure:{exclude:'account'},quota_exhausted:{exclude:'account'},rate_limit:{exclude:'account',requires_rate_limit_policy:true},capacity_unavailable:{exclude:'candidate'},execution_failure:{exclude:'candidate'},policy_rejection:{exclude:'candidate'}};
function candidateKey(c){return c&&typeof c==='object'?[c.provider_id,c.account_id,c.model_id].join('|'):'';}
function compareCandidates(a,b){return a.provider_id.localeCompare(b.provider_id)||a.account_id.localeCompare(b.account_id)||a.model_id.localeCompare(b.model_id);}
function noFallback(){return{status:NO_FALLBACK};}
function selectedShape(status,c,capability){return{status,provider_id:c.provider_id,account_id:c.account_id,model_id:c.model_id,capability};}
function realDeps(){return{route:router.route,collectCandidates:router.collectCandidates,capacityAllows:router.capacityAllows,isAccountActive:accountLookup.isAccountActive,supports:capLookup.supports,getModel:modelLookup.getModel,credentialRefOf:accountLookup.credentialRefOf};}
function mergeDeps(overrides){const base=realDeps();return overrides&&typeof overrides==='object'?Object.assign(base,overrides):base;}
function isCredentialReference(value){if(typeof value!=='string'||value.trim()==='')return false;if(/^(sk-|or-v1-|AIza|Bearer\s+)/i.test(value))return false;return value.startsWith('secret://')||value.startsWith('env://');}
function isCredentialAuthorized(accountId,deps){return isCredentialReference(deps.credentialRefOf(accountId));}
function unauthorizedKeys(policy){const set=new Set();if(!policy||!Array.isArray(policy.unauthorized))return set;for(const item of policy.unauthorized){if(typeof item==='string')set.add(item);else if(item&&typeof item==='object')set.add(candidateKey(item));}return set;}
function visitedKeys(input,primary){const set=new Set();for(const item of input&&Array.isArray(input.visited)?input.visited:[]){if(typeof item==='string')set.add(item);else if(item&&typeof item==='object')set.add(candidateKey(item));}if(primary)set.add(candidateKey(primary));return set;}
function activationAllows(kind,policy){if(policy&&policy.allow_fallback===false)return false;if(!kind)return true;if(!Object.prototype.hasOwnProperty.call(ACTIVATIONS,kind))return false;if(ACTIVATIONS[kind].requires_rate_limit_policy)return!!(policy&&policy.allow_rate_limit_fallback===true);return true;}
function excludedByActivation(candidate,primary,kind){if(!kind||!primary)return false;const spec=ACTIVATIONS[kind];if(!spec)return false;if(spec.exclude==='provider')return candidate.provider_id===primary.provider_id;if(spec.exclude==='account')return candidate.account_id===primary.account_id;if(spec.exclude==='candidate')return candidateKey(candidate)===candidateKey(primary);return false;}
function candidateSelectable(c,capability,deps,policy){if(!c||typeof c!=='object'||!c.provider_id||!c.account_id||!c.model_id||!capability)return false;if(unauthorizedKeys(policy).has(candidateKey(c)))return false;if(!deps.isAccountActive(c.account_id))return false;if(!isCredentialAuthorized(c.account_id,deps))return false;const model=deps.getModel(c.model_id);if(!model||model.status&&model.status!=='available'||model.provider_id&&model.provider_id!==c.provider_id)return false;if(deps.supports(c.model_id,capability)!==true)return false;if(!deps.capacityAllows(c.account_id,c.model_id))return false;return true;}
function applyPreferences(candidates,input){let pool=candidates;if(input.preferred_provider){const x=pool.filter(c=>c.provider_id===input.preferred_provider);if(x.length)pool=x;}if(input.preferred_account){const x=pool.filter(c=>c.account_id===input.preferred_account);if(x.length)pool=x;}if(input.preferred_model){const x=pool.filter(c=>c.model_id===input.preferred_model);if(x.length)pool=x;}return pool;}
function resolvePrimary(input,deps){if(input.router_result&&typeof input.router_result==='object')return input.router_result;return deps.route({capability:input.capability,preferred_provider:input.preferred_provider,preferred_account:input.preferred_account,preferred_model:input.preferred_model});}
function resolve(input,depsOverride){if(!input||typeof input!=='object')return noFallback();const deps=mergeDeps(depsOverride);const policy=input.policy&&typeof input.policy==='object'?input.policy:null;const primary=resolvePrimary(input,deps);if(!primary||primary.status!=='selected')return noFallback();const capability=(primary.capability||input.capability||'').trim();if(!capability)return noFallback();const failureKind=input.failure&&input.failure.kind;if(!failureKind&&candidateSelectable(primary,capability,deps,policy))return selectedShape(PRIMARY,primary,capability);if(!activationAllows(failureKind,policy))return noFallback();const pool=deps.collectCandidates(capability);if(!Array.isArray(pool)||!pool.length)return noFallback();const seen=visitedKeys(input,primary);const remaining=[];for(const c of pool){const key=candidateKey(c);if(!key||seen.has(key)||excludedByActivation(c,primary,failureKind)||!candidateSelectable(c,capability,deps,policy))continue;remaining.push({provider_id:c.provider_id,account_id:c.account_id,model_id:c.model_id});}remaining.sort(compareCandidates);const chosen=applyPreferences(remaining,input)[0];return chosen?selectedShape(FALLBACK,chosen,capability):noFallback();}
module.exports={version:registry.version,resolve,candidateKey,candidateSelectable,activationAllows,POLICY_NOTE,registry};
