import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const URL=Deno.env.get("SUPABASE_URL")!;const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const SECRET=Deno.env.get("ARIA_RUNTIME_SHARED_SECRET")??"";const GOOGLE_API_KEY=Deno.env.get("GOOGLE_API_KEY")??"";
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const bearer=(r:Request)=>{const h=r.headers.get("authorization")??"";return h.startsWith("Bearer ")?h.slice(7):null};
const eq=(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0};
async function auth(r:Request){const b=bearer(r);if(b&&SECRET&&eq(b,SECRET))return true;const t=r.headers.get("x-aria-autonomy-token");if(!t)return false;const {data,error}=await sb.rpc("aria_autonomy_cron_authorize",{p_token:t});return !error&&data===true}
async function secret(name:string){const {data,error}=await sb.rpc("read_aria_credential_secret",{p_name:name});if(error||typeof data!=="string"||!data)return null;return data}
const sanitize=(m:unknown)=>String(m??"error").replace(/Bearer\s+[A-Za-z0-9._-]+/g,"[redacted]").replace(/\bsk-[A-Za-z0-9_-]{8,}\b/g,"[redacted]").replace(/AIza[A-Za-z0-9_-]{20,}/g,"[redacted]").replace(/\bor-v1-[A-Za-z0-9_-]{8,}\b/g,"[redacted]");
async function directGemini(route:any,input:any){
  if(route.capability!=="text_generation")return out({status:"blocked",reason:"capability_missing"});
  if(route.account_id!=="acct_google_gemini_free")return out({status:"blocked",reason:"route_not_selectable"});
  if(route.model_id!=="google/gemini-3.5-flash-lite-direct")return out({status:"blocked",reason:"model_not_verified"});
  if(!GOOGLE_API_KEY)return out({status:"failed",error:{code:"credential_unavailable",message:"google credential unavailable"}});
  const p=input?.payload??{};const model="gemini-3.5-flash-lite";const contents=Array.isArray(p.contents)&&p.contents.length?p.contents:(typeof p.prompt==="string"&&p.prompt.length?[{role:"user",parts:[{text:p.prompt}]}]:null);
  if(!contents)return out({status:"blocked",reason:"input_missing"});
  const body:any={contents};if(p.systemInstruction)body.systemInstruction=p.systemInstruction;if(p.generationConfig)body.generationConfig={...p.generationConfig};
  if(body.generationConfig?.temperature!==undefined){const {temperature,...rest}=body.generationConfig;body.generationConfig=rest;}
  if(body.generationConfig?.topP!==undefined){const {topP,...rest}=body.generationConfig;body.generationConfig=rest;}
  if(body.generationConfig?.topK!==undefined){const {topK,...rest}=body.generationConfig;body.generationConfig=rest;}
  let res:Response;try{res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":GOOGLE_API_KEY},body:JSON.stringify(body)})}catch{return out({status:"failed",error:{code:"transport_error",message:"transport failure"}})}
  const json=await res.json().catch(()=>null);if(!res.ok)return out({status:"failed",error:{code:"provider_error",message:sanitize(json?.error?.message||`provider returned HTTP ${res.status}`),provider_status:res.status}});
  const parts=json?.candidates?.[0]?.content?.parts;const text=Array.isArray(parts)?parts.filter((x:any)=>typeof x?.text==="string").map((x:any)=>x.text).join(""):"";
  if(!text)return out({status:"failed",error:{code:"invalid_response",message:"no text content in provider response"}});
  return out({status:"succeeded",response:{modality:"text",content:text,provider_response_id:null,finish_reason:json?.candidates?.[0]?.finishReason??null,provider_model:route.model_id},usage:json?.usageMetadata?{status:"known",prompt_tokens:json.usageMetadata.promptTokenCount??null,completion_tokens:json.usageMetadata.candidatesTokenCount??null,total_tokens:json.usageMetadata.totalTokenCount??null}:{status:"unknown"},metadata:{runtime:"aria-execution-runtime-v1",adapter_id:"google_gemini_generate_content",provider_id:"google",route_type:"direct",attempt:1,canonical_write:false,memory_authority:"none"}});
}
Deno.serve(async r=>{if(r.method!=="POST")return out({error:"method_not_allowed"},405);if(!(await auth(r)))return out({error:"unauthorized"},401);const body=await r.json().catch(()=>({}));const route=body?.selected_route;const input=body?.input;const az=body?.authorization;if(!route||typeof route!=="object")return out({status:"blocked",reason:"route_missing"});if(!az||az.status!=="approved")return out({status:"blocked",reason:"authorization_not_approved"});if(route.provider_id==="google")return directGemini(route,input);if(route.provider_id!=="openrouter")return out({status:"blocked",reason:"adapter_unavailable"});if(route.capability!=="text_generation")return out({status:"blocked",reason:"capability_missing"});if(route.account_id!=="acct_openrouter_primary")return out({status:"blocked",reason:"route_not_selectable"});if(route.model_id!=="google/gemini-2.5-flash-lite")return out({status:"blocked",reason:"model_not_verified"});const sec=await secret("aria_openrouter_primary");if(!sec)return out({status:"failed",error:{code:"credential_unavailable",message:"credential unavailable"}});const p=input?.payload;const messages=Array.isArray(p?.messages)&&p.messages.length?p.messages:(typeof p?.prompt==="string"&&p.prompt.length?[{role:"user",content:p.prompt}]:null);if(!messages)return out({status:"blocked",reason:"input_missing"});const reqBody:any={model:route.model_id,messages};if(typeof p.max_tokens==="number")reqBody.max_tokens=p.max_tokens;if(typeof p.temperature==="number")reqBody.temperature=p.temperature;let res:Response;try{res=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${sec}`,"Content-Type":"application/json"},body:JSON.stringify(reqBody)})}catch{return out({status:"failed",error:{code:"transport_error",message:"transport failure"}})}const json=await res.json().catch(()=>null);if(!res.ok)return out({status:"failed",error:{code:"provider_error",message:sanitize(json?.error?.message||`provider returned HTTP ${res.status}`),provider_status:res.status}});const c=json?.choices?.[0]?.message?.content;if(typeof c!=="string")return out({status:"failed",error:{code:"invalid_response",message:"no text content in provider response"}});return out({status:"succeeded",response:{modality:"text",content:c,provider_response_id:typeof json?.id==="string"?json.id:null,finish_reason:typeof json?.choices?.[0]?.finish_reason==="string"?json.choices[0].finish_reason:null,provider_model:typeof json?.model==="string"?json.model:null},usage:json?.usage??{status:"unknown"},metadata:{runtime:"aria-execution-runtime-v1",adapter_id:"openrouter_chat_completions",provider_id:"openrouter",route_type:"mediated",attempt:1,canonical_write:false,memory_authority:"none"}})});
