import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { verifyStrategicCompletion } from "../_shared/strategic-goal-completion.mjs";
import { githubRead, githubCreateBranch, githubWrite, githubPr } from "../_shared/github-app.mjs";
const URL=Deno.env.get("SUPABASE_URL")!,KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,SECRET=Deno.env.get("ARIA_RUNTIME_SHARED_SECRET")??"";
const MEMORY=`${URL}/functions/v1/aria-memory-v2`,PLANNER=`${URL}/functions/v1/aria-planner-v10`,WORKER="https://aria.robvg9.workers.dev";
const sb=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}}),sleep=(m:number)=>new Promise(r=>setTimeout(r,m));
const bearer=(r:Request)=>{const h=r.headers.get("authorization")??"";return h.startsWith("Bearer ")?h.slice(7):null};
const equal=(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0};
async function rpc(n:string,a:Record<string,unknown>){const{data,error}=await sb.rpc(n,a);if(error)throw new Error(`${n}:${error.message}`);return data}
async function auth(r:Request){const d=bearer(r);if(d&&SECRET&&equal(d,SECRET))return true;const t=r.headers.get("x-aria-autonomy-token");return !!t&&(await rpc("aria_autonomy_cron_authorize",{p_token:t}))===true}
async function recall(goal:string,t:string|null){const h:Record<string,string>={"content-type":"application/json"};if(t)h["x-aria-autonomy-token"]=t;else if(SECRET)h.authorization=`Bearer ${SECRET}`;try{const r=await fetch(MEMORY,{method:"POST",headers:h,body:JSON.stringify({action:"search",query:goal,limit:8})}),b=await r.json().catch(()=>null);return{available:r.ok&&b?.ok===true,results:r.ok&&Array.isArray(b?.results)?b.results:[],error:r.ok&&b?.ok===true?null:`memory_${r.status}`}}catch(e){return{available:false,results:[],error:e instanceof Error?e.message:String(e)}}}
async function plan(goal:string,t:string|null,c:unknown){const h:Record<string,string>={"content-type":"application/json"};if(t)h["x-aria-autonomy-token"]=t;else if(SECRET)h.authorization=`Bearer ${SECRET}`;const r=await fetch(PLANNER,{method:"POST",headers:h,body:JSON.stringify({goal,context:c})}),b=await r.json().catch(()=>null);if(!r.ok||!b?.ok||!Array.isArray(b.plan?.steps))throw new Error(`planner_${r.status}`);return b.plan}
const emit=(id:string,type:string,payload:unknown)=>rpc("aria_mission_append_event",{p_mission_id:id,p_event:{event_type:type,payload}}),update=(id:string,m:Record<string,unknown>)=>rpc("aria_mission_update",{p_mission_id:id,p_mission:m});
async function cf(op:string){const r=await fetch(`${WORKER}/`,{headers:{"user-agent":"ARIA-cognitive-runner-v17"}}).catch(()=>null);if(r?.ok)return{ok:true,status:r.status,executor_type:"connector",connector_id:"cloudflare",operation:op,mode:"worker_root_liveness"};throw new Error(`cloudflare_unavailable_${r?.status??"network"}`)}
async function sub(id:string,op:string){if(op==="health")return{ok:true,status:200,executor_type:"connector",connector_id:"supabase",operation:op};if(op==="mission_read")return{ok:true,status:200,executor_type:"connector",connector_id:"supabase",operation:op,data:await rpc("aria_mission_get",{p_mission_id:id})};throw new Error(`supabase_operation_not_allowed:${op}`)}
function autonomousBranch(id:string){return`aria/autonomous/${String(id).replace(/[^a-zA-Z0-9_-]/g,"").slice(0,80)}`}
async function stepExec(id:string,s:any){const t=String(s.executor_type||s.target?.type||"connector");if(t!=="connector")throw new Error(`unsupported_executor:${t}`);const c=String(s.target?.connector_id||s.connector_id||""),op=String(s.operation||"");if(c==="github"){if(op==="file_read")return githubRead(String(s.input?.path||s.path||"README.md"),String(s.input?.ref||s.ref||"main"));if(op==="branch_create")return githubCreateBranch({branch:String(s.input?.branch||s.branch||autonomousBranch(id)),base:String(s.input?.base||s.base||"main")});if(op==="file_write")return githubWrite({path:String(s.input?.path||s.path||""),content:String(s.input?.content??s.content??""),branch:String(s.input?.branch||s.branch||autonomousBranch(id)),base:String(s.input?.base||s.base||"main"),message:String(s.input?.message||s.message||`ARIA autonomous change for ${id}`)});if(op==="pull_request_create")return githubPr({branch:String(s.input?.branch||s.branch||autonomousBranch(id)),base:String(s.input?.base||s.base||"main"),title:String(s.input?.title||s.title||"ARIA autonomous change"),body:String(s.input?.body||s.body||`Automated change proposed by ARIA for mission ${id}. Human review required before merge.`),draft:Boolean(s.input?.draft??s.draft??false)});throw new Error(`github_operation_not_allowed:${op}`)}if(c==="cloudflare")return cf(op||"worker_read");if(c==="supabase")return sub(id,op||"mission_read");throw new Error(`unsupported_connector:${c}`)}
const READ_ONLY=new Set(["file_read","account_read","content_read","deployment_read","worker_read","health","mission_read"]);
function depsReady(step:any,done:Set<string>){return Array.isArray(step?.depends_on)?step.depends_on.every((d:any)=>done.has(String(d))):true}
function isParallelSafe(step:any){const op=String(step?.operation||"").toLowerCase();const risk=String(step?.risk||"").toUpperCase();return risk==="READ"||READ_ONLY.has(op)}
function readyBatch(steps:any[],done:Set<string>,limit:number){return steps.filter(s=>!done.has(String(s.id))&&depsReady(s,done)).slice(0,limit)}
async function executeOne(id:string,s:any,attempts:any){const sid=String(s.id),risk=String(s.risk||"");let a=Number(attempts[sid]||0),pass=false,res:any=null;while(a<3&&!pass){a++;attempts[sid]=a;await emit(id,"step_started",{step_id:sid,operation:s.operation,executor_type:s.executor_type||s.target?.type||"connector",attempt:a,risk});try{res=await stepExec(id,s)}catch(e){res={status:"failed",stderr:e instanceof Error?e.message:String(e),executor_type:s.executor_type||s.target?.type||"connector",operation:s.operation,attempt:a}}pass=res?.status==="succeeded"||(res?.ok===true&&res?.status!=="waiting");if(pass){await emit(id,"step_succeeded",{step_id:sid,executor_type:res.executor_type,connector_id:res.connector_id||null,operation:res.operation||s.operation||null,attempt:a});break}await emit(id,"step_failed",{step_id:sid,attempt:a,retryable:a<3,executor_type:res?.executor_type,connector_id:res?.connector_id||null,operation:res?.operation||s.operation||null,reason:res?.stderr||res?.error||res?.status||"unknown"});if(a<3)await sleep(200*a)}return{step:s,outcome:{result:res,passed:pass,attempt:a},pass}}
Deno.serve(async r=>{if(r.method!=="POST")return out({error:"method_not_allowed"},405);if(!(await auth(r)))return out({error:"unauthorized"},401);const b=await r.json().catch(()=>({}));try{const recovered=await rpc("aria_autonomy_recover_stale_missions",{p_stale_after:"00:02:00"}),m=typeof b.mission_id==="string"?await rpc("aria_mission_get",{p_mission_id:b.mission_id}):await rpc("aria_mission_claim_next_lease",{p_worker_id:"aria-mission-runner-v17",p_lease_for:"00:02:00"});if(!m)return out({ok:true,status:"idle",recovered});const id=m.mission_id,goal=String(m.goal||""),token=r.headers.get("x-aria-autonomy-token"),c=await recall(goal,token),ctx={version:"cognitive-loop-v2",available:c.available,recall_count:c.results.length,memory_ids:c.results.map((x:any)=>x.memory_id||x.id).filter(Boolean),recalled_memories:c.results.slice(0,8),error:c.error};await emit(id,"cognitive_recall_completed",ctx);const cp={...(m.checkpoint||{}),cognitive_context:ctx,cognitive_loop:{version:"cognitive-loop-v2",recalled_before_planning:true}};await update(id,{status:"planning",checkpoint:cp});const p=Array.isArray(cp.plan)&&cp.plan.length?{steps:cp.plan}:(await plan(goal,token,ctx)),steps=p.steps||[];if(!steps.length)throw new Error("planner_empty_steps");const checkpoint={...cp,plan:steps},done=new Set<string>(Array.isArray(checkpoint.completed_steps)?checkpoint.completed_steps.map(String):[]),attempts:Record<string,number>=checkpoint.attempts&&typeof checkpoint.attempts==="object"?{...checkpoint.attempts}:{};await update(id,{status:"running",total_steps:steps.length,current_step:done.size,checkpoint});await emit(id,"cognitive_planning_context_used",{recall_count:ctx.recall_count,memory_ids:ctx.memory_ids,planner_context_version:"cognitive-loop-v2"});
while(done.size<steps.length){const unresolved=steps.filter((s:any)=>!done.has(String(s.id)));const ready=readyBatch(unresolved,done,2);if(!ready.length){const blocked=unresolved.find((s:any)=>!depsReady(s,done));const reason=blocked?`dependencies_unsatisfied:${blocked.id}`:"no_ready_step";await update(id,{status:"blocked",next_action:"recovery: dependency_dead_letter",last_stderr:reason,lease_owner:null,lease_until:null,checkpoint:{...checkpoint,completed_steps:[...done],attempts,dependency_blocked:true}});await emit(id,"mission_dead_lettered",{reason});return out({ok:false,status:"blocked",mission_id:id,reason})}const batch=ready.length>1&&ready.every(isParallelSafe)?ready:ready.slice(0,1);await emit(id,"step_batch_started",{batch_id:`batch_${done.size+1}`,step_ids:batch.map((s:any)=>String(s.id)),parallel:batch.length>1,max_parallel:2});const results=await Promise.all(batch.map((s:any)=>executeOne(id,s,attempts)));const failures=results.filter(x=>!x.pass);for(const item of results)if(item.pass)done.add(String(item.step.id));await update(id,{current_step:done.size,completed_steps:done.size,next_action:done.size<steps.length?"next_ready_batch":"verify_goal",checkpoint:{...checkpoint,completed_steps:[...done],attempts,active_steps:[],last_batch:batch.map((s:any)=>String(s.id)),parallel_batch:batch.length>1}});if(failures.length){const f=failures[0];const dl={step_id:String(f.step.id),attempts:f.outcome.attempt,reason:"max_attempts_exhausted"};await update(id,{status:"blocked",next_action:"recovery: dead_letter",last_stderr:dl.reason,lease_owner:null,lease_until:null,checkpoint:{...checkpoint,completed_steps:[...done],attempts,dead_letter:dl}});await emit(id,"mission_dead_lettered",dl);return out({ok:false,status:"blocked",mission_id:id,reason:"dead_letter"})}}
const completion=verifyStrategicCompletion({goal,goalSource:m.metadata?.goal_source,steps});if(!completion.verified){const evidence={...completion,goal_source:m.metadata?.goal_source||null,steps:steps.map((s:any)=>({id:s.id,operation:s.operation,risk:s.risk||null,executor_type:s.executor_type||s.target?.type||"connector"}))};await update(id,{status:"blocked",next_action:"recovery: planner_replan_required",last_stderr:completion.reason,lease_owner:null,lease_until:null,checkpoint:{...checkpoint,completed_steps:[...done],attempts,strategic_completion:evidence}});await emit(id,"mission_goal_completion_insufficient",evidence);return out({ok:false,status:"blocked",mission_id:id,reason:completion.reason})}await emit(id,"mission_verified",{steps:steps.length,executor_types:[...new Set(steps.map((s:any)=>s.executor_type||s.target?.type||"connector"))],goal_completion:completion});await emit(id,"cognitive_loop_completed",{version:"cognitive-loop-v2",recall_count:ctx.recall_count,memory_ids:ctx.memory_ids,steps:steps.length,recovered,verified:true});await update(id,{status:"succeeded",current_step:steps.length,completed_steps:steps.length,next_action:null,lease_owner:null,lease_until:null,finished_at:new Date().toISOString(),checkpoint:{...checkpoint,completed_steps:steps.map((s:any)=>String(s.id)),attempts,active_steps:[],parallel_execution:true,cognitive_loop_completed:true,strategic_completion:completion}});await emit(id,"mission_succeeded",{steps:steps.length});return out({ok:true,status:"succeeded",mission_id:id,steps:steps.length,cognitive:{recall_count:ctx.recall_count,memory_ids:ctx.memory_ids}})}catch(e){const reason=e instanceof Error?e.message:String(e);if(typeof b.mission_id==="string")try{await update(b.mission_id,{status:"paused",next_action:"recovery: runner exception",last_stderr:reason})}catch(_){}return out({ok:false,status:"paused",reason},200)}});
