import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL"),SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),SHARED_SECRET=Deno.env.get("ARIA_RUNTIME_SHARED_SECRET");
if(!SUPABASE_URL||!SERVICE_ROLE_KEY||!SHARED_SECRET)throw new Error("ARIA runtime gateway is not configured");
const supabase=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const eq=async(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0};
const SAFE=new Set(["reliability","performance","documentation","observability","capability_gap","regression"]);
const classify=(s:Record<string,unknown>)=>{const risk=String(s.risk||"LOW").toUpperCase(),category=String(s.category||"capability_gap"),blocked=s.destructive===true||["HIGH","CRITICAL"].includes(risk)||s.production===true||s.external_authority===true||s.physical===true||!SAFE.has(category);return{executable:!blocked,category,risk,human_gate_required:blocked,reasons:blocked?[!SAFE.has(category)?"category_not_autonomous":"autonomy_frontier"]:[]}};
const sanitize=(job:Record<string,unknown>|null)=>{if(!job)return null;const allowed=["job_id","mission_id","device_id","operation","status","attempt","max_attempts","timeout_ms","created_at","started_at","completed_at","exit_code","stdout","stderr","result","metadata"];return Object.fromEntries(Object.entries(job).filter(([k])=>allowed.includes(k)))};
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const a=req.headers.get("authorization")||"";if(!a.startsWith("Bearer ")||!(await eq(a.slice(7),SHARED_SECRET)))return json({error:"unauthorized"},401);let body:Record<string,unknown>;try{body=await req.json()}catch{return json({error:"invalid_json"},400)};const action=body.action;
if(action==="self_improve"){const signal=body.signal&&typeof body.signal==="object"?body.signal as Record<string,unknown>:{};const goal=typeof signal.goal==="string"?signal.goal.trim().slice(0,1000):"";if(!goal)return json({error:"invalid_request",field:"signal.goal"},400);const classification=classify(signal);const approvals={promote:false,deploy:false};if(!classification.executable)return json({ok:true,action,status:"blocked",version:"self-improvement-runtime-v1",goal,classification,approvals,stop_reason:"autonomy_frontier"});return json({ok:true,action,status:"accepted",version:"self-improvement-runtime-v1",goal,classification,approvals,pipeline:["observe","research","plan","build","test","security","evaluate","verify","learn"],promotion:"human_gate",deployment:"human_gate",execution:"governed_contract_only"})}
if(action!=="enqueue_device_job"&&action!=="get_job")return json({error:"unsupported_action"},400);
if(action==="enqueue_device_job"){for(const k of ["job_id","mission_id","device_id","operation","command"])if(typeof body[k]!=="string"||!(body[k] as string).trim())return json({error:"invalid_request",field:k},400);const{data,error}=await supabase.rpc("enqueue_execution_job_gateway",{p_job_id:body.job_id,p_mission_id:body.mission_id,p_device_id:body.device_id,p_operation:body.operation,p_command:body.command,p_cwd:typeof body.cwd==="string"?body.cwd:null,p_timeout_ms:Number.isInteger(body.timeout_ms)?body.timeout_ms:120000,p_policy:body.policy&&typeof body.policy==="object"?body.policy:{},p_metadata:body.metadata&&typeof body.metadata==="object"?body.metadata:{}});if(error)return json({error:"enqueue_failed",detail:error.message},500);return json({ok:true,action,job:sanitize(data)})}
if(typeof body.job_id!=="string"||!body.job_id.trim())return json({error:"invalid_request",field:"job_id"},400);const{data,error}=await supabase.rpc("get_execution_job_gateway",{p_job_id:body.job_id});if(error)return json({error:"get_job_failed",detail:error.message},500);return json({ok:true,action,job:sanitize(data)})});
