import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SECRET=Deno.env.get("ARIA_RUNTIME_SHARED_SECRET")??"";
const APP_ID=Number(Deno.env.get("ARIA_GITHUB_APP_ID")??"4835157");
const API="https://api.github.com";
const DEFAULT_OWNER=Deno.env.get("ARIA_GITHUB_OWNER")??"Robvg9";
const DEFAULT_REPO=Deno.env.get("ARIA_GITHUB_REPOSITORY")??"aria-worker";
const ALLOWED=new Set((Deno.env.get("ARIA_GITHUB_ALLOWED_REPOS")??"Robvg9/aria-worker,Robvg9/battlecruiser").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean));
const out=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const eq=(a:string,b:string)=>{const x=new TextEncoder().encode(a),y=new TextEncoder().encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0};
const tok=(r:Request)=>{const h=r.headers.get("authorization")??"";return h.startsWith("Bearer ")?h.slice(7):r.headers.get("x-aria-autonomy-token")};
async function auth(r:Request){const t=tok(r);return!!(t&&SECRET&&eq(t,SECRET))}
function b64(s:string){const c=s.replace(/\s+/g,"").replace(/-/g,"+").replace(/_/g,"/");const p=c+"=".repeat((4-c.length%4)%4);return Uint8Array.from(atob(p),x=>x.charCodeAt(0))}
function u64(b:Uint8Array){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}
function u64j(v:unknown){return u64(new TextEncoder().encode(JSON.stringify(v)))}
function der(t:number,c:Uint8Array){const n=c.length,l=n<128?Uint8Array.of(n):(()=>{const a:number[]=[];for(let x=n;x;x>>>=8)a.unshift(x&255);return Uint8Array.of(0x80|a.length,...a)})();const o=new Uint8Array(1+l.length+c.length);o[0]=t;o.set(l,1);o.set(c,1+l.length);return o}
function cat(...xs:Uint8Array[]){const n=xs.reduce((a,b)=>a+b.length,0),o=new Uint8Array(n);let i=0;for(const x of xs){o.set(x,i);i+=x.length}return o}
function pkcs1To8(k:Uint8Array){const oid=Uint8Array.of(6,9,42,134,72,134,247,13,1,1,1);return der(48,cat(der(2,Uint8Array.of(0)),der(48,cat(oid,Uint8Array.of(5,0))),der(4,k)))}
async function appJwt(){const pk=Deno.env.get("ARIA_GITHUB_APP_PRIVATE_KEY")??"";if(!pk)throw new Error("github_app_private_key_missing");const raw=b64(pk.replace(/-----BEGIN (?:RSA )?PRIVATE KEY-----/g,"").replace(/-----END (?:RSA )?PRIVATE KEY-----/g,""));const keyDer=pk.includes("BEGIN RSA PRIVATE KEY")?pkcs1To8(raw):raw;const key=await crypto.subtle.importKey("pkcs8",keyDer.buffer,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const now=Math.floor(Date.now()/1000),h=u64j({alg:"RS256",typ:"JWT"}),p=u64j({iat:now-30,exp:now+540,iss:APP_ID}),sig=new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(`${h}.${p}`)));return`${h}.${p}.${u64(sig)}`}
async function gh(path:string,init:RequestInit={},token:string){const r=await fetch(API+path,{...init,headers:{accept:"application/vnd.github+json",authorization:`Bearer ${token}`,"X-GitHub-Api-Version":"2022-11-28","content-type":"application/json","user-agent":"ARIA-github-app-runtime-v1",...(init.headers||{})}});const j:any=await r.json().catch(()=>null);if(!r.ok)throw new Error(`github_${r.status}:${j?.message??"request_failed"}`);return j}
async function discoverInstallation(){const jwt=await appJwt(),list=await gh("/app/installations",{},jwt),wanted=Array.isArray(list)?list.find((x:any)=>String(x?.account?.login??"").toLowerCase()===DEFAULT_OWNER.toLowerCase()):null;if(!wanted?.id)throw new Error(`github_installation_not_found:${DEFAULT_OWNER}`);return{id:Number(wanted.id),account:String(wanted.account?.login??DEFAULT_OWNER)}}
async function installationToken(repository:string){const installation=await discoverInstallation(),jwt=await appJwt(),r=await fetch(`${API}/app/installations/${installation.id}/access_tokens`,{method:"POST",headers:{accept:"application/vnd.github+json",authorization:`Bearer ${jwt}`,"X-GitHub-Api-Version":"2022-11-28","content-type":"application/json","user-agent":"ARIA-github-app-runtime-v1"},body:JSON.stringify({repositories:[repository]})}),j:any=await r.json().catch(()=>null);if(!r.ok||!j?.token)throw new Error(`github_installation_token_${r.status}:${j?.message??"request_failed"}`);return{token:String(j.token),expires_at:j.expires_at??null,installation_id:installation.id,account:installation.account}}
function repo(b:any){const owner=String(b.owner??DEFAULT_OWNER),rp=String(b.repo??DEFAULT_REPO);if(!/^[A-Za-z0-9_.-]+$/.test(owner)||!/^[A-Za-z0-9_.-]+$/.test(rp)||!ALLOWED.has(`${owner}/${rp}`.toLowerCase()))throw new Error("repository_not_allowlisted");return{owner,repo:rp}}
function pathSafe(p:string){const x=String(p||"").replace(/^\/+/,"");if(!x||x.includes("..")||x.includes(".git/")||x.startsWith(".github/workflows/"))throw new Error("unsafe_path");return x}
Deno.serve(async r=>{if(r.method!=="POST")return out({error:"method_not_allowed"},405);if(!(await auth(r)))return out({error:"unauthorized"},401);try{const b:any=await r.json().catch(()=>({})),op=String(b.operation||""),{owner,repo:rp}=repo(b),installation=await discoverInstallation(),t=await installationToken(rp);
if(op==="installation_info")return out({ok:true,status:200,executor_type:"github_app",connector_id:"github",operation:op,data:await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/installation`,{},t.token),installation_id:installation.id,account:installation.account});
if(op==="repo_read")return out({ok:true,status:200,executor_type:"github_app",connector_id:"github",operation:op,data:await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}`,{},t.token),installation_id:installation.id,account:installation.account});

if(op==="tree_read"){
  const branch=String(b.branch||b.ref||b.base||"main");
  const ref=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/git/ref/heads/${encodeURIComponent(branch)}`,{},t.token);
  const sha=String(ref?.object?.sha||"");
  if(!sha)throw new Error("github_tree_ref_missing");
  const tree=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/git/trees/${encodeURIComponent(sha)}?recursive=1`,{},t.token);
  return out({ok:true,status:200,executor_type:"github_app",connector_id:"github",operation:op,data:{branch,sha,truncated:tree?.truncated===true,paths:Array.isArray(tree?.tree)?tree.tree.filter((x:any)=>x?.type==="blob").map((x:any)=>String(x.path||"")).slice(0,5000):[]},installation_id:installation.id,account:installation.account});
}

if(op==="code_search"){
  const query=String(b.query||"").trim();
  if(!query)throw new Error("github_code_search_query_missing");
  const scoped=`${query} repo:${owner}/${rp}`;
  const result=await gh(`/search/code?q=${encodeURIComponent(scoped)}&per_page=30`,{},t.token);
  return out({ok:true,status:200,executor_type:"github_app",connector_id:"github",operation:op,data:{total_count:Number(result?.total_count||0),items:Array.isArray(result?.items)?result.items.slice(0,30):[]},installation_id:installation.id,account:installation.account});
}
if(op==="file_read"){const ref=String(b.branch||b.ref||b.base||"main"),p=pathSafe(b.path);return out({ok:true,status:200,executor_type:"github_app",connector_id:"github",operation:op,data:await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/contents/${p}?ref=${encodeURIComponent(ref)}`,{},t.token),installation_id:installation.id,account:installation.account})}
if(op==="create_branch"){const branch=String(b.branch||""),ref=String(b.ref||b.base||"main");if(!branch||["main","master"].includes(branch)||!/^[A-Za-z0-9._\/-]{1,200}$/.test(branch)||branch.includes(".."))throw new Error("invalid_branch");const source=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/git/ref/heads/${encodeURIComponent(ref)}`,{},t.token);try{const created=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/git/refs`,{method:"POST",body:JSON.stringify({ref:`refs/heads/${branch}`,sha:source.object?.sha})},t.token);return out({ok:true,status:201,executor_type:"github_app",connector_id:"github",operation:op,data:created,installation_id:installation.id,account:installation.account})}catch(e){const msg=String(e instanceof Error?e.message:e);if(!msg.startsWith("github_422:"))throw e;const existing=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/git/ref/heads/${encodeURIComponent(branch)}`,{},t.token);if(existing?.object?.sha!==source?.object?.sha)throw new Error("branch_conflict_existing_different_base");return out({ok:true,status:200,executor_type:"github_app",connector_id:"github",operation:op,data:existing,installation_id:installation.id,account:installation.account,idempotent:true})}}
if(op==="file_write"){const branch=String(b.branch||""),p=pathSafe(b.path),content=String(b.content??"");if(!branch||["main","master"].includes(branch))throw new Error("write_branch_required");if(String(b.risk_level||"low")!=="low")throw new Error("risk_not_allowed");let existing:any=null;try{existing=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/contents/${p}?ref=${encodeURIComponent(branch)}`,{},t.token)}catch(e){if(!String(e instanceof Error?e.message:e).startsWith("github_404:"))throw e}const payload:any={message:String(b.message||"chore: ARIA governed repair"),content:btoa(unescape(encodeURIComponent(content))),branch};if(existing?.sha)payload.sha=existing.sha;const written=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/contents/${p}`,{method:"PUT",body:JSON.stringify(payload)},t.token);return out({ok:true,status:201,executor_type:"github_app",connector_id:"github",operation:op,data:{commit_sha:written?.commit?.sha??null,path:p,branch},installation_id:installation.id,account:installation.account})}
if(op==="open_pr"){const branch=String(b.branch||""),base=String(b.base||"main");if(!branch||["main","master"].includes(branch))throw new Error("pr_branch_required");const existing=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/pulls?head=${encodeURIComponent(owner+":"+branch)}&base=${encodeURIComponent(base)}&state=open`,{},t.token);if(Array.isArray(existing)&&existing.length)return out({ok:true,status:200,executor_type:"github_app",connector_id:"github",operation:op,data:{number:existing[0]?.number??null,url:existing[0]?.html_url??null},installation_id:installation.id,account:installation.account,idempotent:true});const pr=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(rp)}/pulls`,{method:"POST",body:JSON.stringify({title:String(b.title||"chore: ARIA governed change"),body:String(b.body||"Generated by ARIA after governed validation."),head:branch,base})},t.token);return out({ok:true,status:201,executor_type:"github_app",connector_id:"github",operation:op,data:{number:pr?.number??null,url:pr?.html_url??null},installation_id:installation.id,account:installation.account})}
throw new Error("operation_not_allowed")}catch(e){return out({ok:false,status:"failed",error:e instanceof Error?e.message:String(e)},200)}});
