-- ARIA Mission 9.5 — safe end-to-end trace events
-- Observability only. No tokens, secrets, bodies, cookies, or authorization values are stored.

create table if not exists public.aria_mcp_trace_events (
  id bigint generated by default as identity primary key,
  trace_id text not null check (length(trace_id) between 16 and 128),
  parent_trace_id text,
  stage text not null,
  component text not null,
  outcome text not null,
  method text,
  path text,
  status_code integer check (status_code is null or (status_code between 100 and 599)),
  mcp_method text,
  client_id text,
  has_bearer boolean,
  error_code text,
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  details jsonb,
  created_at timestamptz not null default now()
);

alter table public.aria_mcp_oauth_pending add column if not exists trace_id text;
alter table public.aria_mcp_oauth_codes add column if not exists trace_id text;

create index if not exists aria_mcp_trace_events_trace_idx
  on public.aria_mcp_trace_events (trace_id, created_at);
create index if not exists aria_mcp_trace_events_created_idx
  on public.aria_mcp_trace_events (created_at desc);
create index if not exists aria_mcp_oauth_pending_trace_idx
  on public.aria_mcp_oauth_pending (trace_id);
create index if not exists aria_mcp_oauth_codes_trace_idx
  on public.aria_mcp_oauth_codes (trace_id);

alter table public.aria_mcp_trace_events enable row level security;
revoke all on public.aria_mcp_trace_events from anon, authenticated;
grant all on public.aria_mcp_trace_events to service_role;

comment on table public.aria_mcp_trace_events is 'ARIA 9.5 safe diagnostic trace events. Service-role only; never stores OAuth tokens, secrets, request bodies, cookies, or auth headers.';
